In [1]:
import pandas as pd
import numpy as np
import re

from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, RobustScaler, TargetEncoder, FunctionTransformer, LabelEncoder
from sklearn.model_selection import KFold

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


from catboost import CatBoostClassifier
import lightgbm as lgb
import xgboost as xgb

import sklearn
sklearn.set_config(transform_output="pandas")
df = pd.read_csv('rps_data.csv', sep=',')

In [2]:
df['score_diff'] = df['score_me_before'] - df['score_opp_before']
df['is_last_round'] = ((df['score_me_before'] == 2) | (df['score_opp_before'] == 2)).astype(int)

In [3]:
df

,match_id,round,player_name,win_category,opp_match_wins,opp_match_winrate,stake,opp_move,my_move,is_last_round,...,score_me_before,score_opp_before,streak_draws,prev_opp_move,prev_my_move,prev_outcome,prev2_opp_move,prev2_my_move,prev2_outcome,score_diff
0,1,1,Неизвестен,unknown,-1,-0.01,25,Н,Б,0,...,0,0,0,-1,-1,none,-1,-1,none,0
1,1,2,Неизвестен,unknown,-1,-0.01,25,К,Н,0,...,0,1,0,Н,Б,lose,-1,-1,none,-1
2,1,3,Неизвестен,unknown,-1,-0.01,25,Н,Н,1,...,0,2,0,К,Н,lose,Н,Б,lose,-2
3,1,4,Неизвестен,unknown,-1,-0.01,25,Н,Н,1,...,0,2,1,Н,Н,draw,К,Н,lose,-2
4,1,5,Неизвестен,unknown,-1,-0.01,25,Н,К,1,...,0,2,2,Н,Н,draw,Н,Н,draw,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,188,7,Дальний Тайник,<=5,3,0.75,100,Н,Б,1,...,1,2,2,Б,Б,draw,Н,Н,draw,-1
1201,189,1,Дальний Тайник,<=5,4,0.80,50,Н,Б,0,...,0,0,0,-1,-1,none,-1,-1,none,0
1202,189,2,Дальний Тайник,<=5,4,0.80,50,К,Н,0,...,0,1,0,Н,Б,lose,-1,-1,none,-1
1203,189,3,Дальний Тайник,<=5,4,0.80,50,К,К,1,...,0,2,0,К,Н,lose,Н,Б,lose,-2
1204,189,4,Дальний Тайник,<=5,4,0.80,50,Б,К,1,...,0,2,1,К,К,draw,К,Н,lose,-2

In [4]:
df['next_opp_move'] = df.groupby('match_id')['opp_move'].shift(-1)
df_model = df[df['round'] >= 3].copy()
df_model = df_model.dropna(subset=['next_opp_move', 'prev_opp_move', 'prev2_opp_move'])

le = LabelEncoder()
X, y = df_model.drop('next_opp_move', axis=1), le.fit_transform(df_model['next_opp_move'])
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [5]:
df_model

,match_id,round,player_name,win_category,opp_match_wins,opp_match_winrate,stake,opp_move,my_move,is_last_round,...,score_opp_before,streak_draws,prev_opp_move,prev_my_move,prev_outcome,prev2_opp_move,prev2_my_move,prev2_outcome,score_diff,next_opp_move
2,1,3,Неизвестен,unknown,-1,-0.01,25,Н,Н,1,...,2,0,К,Н,lose,Н,Б,lose,-2,Н
3,1,4,Неизвестен,unknown,-1,-0.01,25,Н,Н,1,...,2,1,Н,Н,draw,К,Н,lose,-2,Н
4,1,5,Неизвестен,unknown,-1,-0.01,25,Н,К,1,...,2,2,Н,Н,draw,Н,Н,draw,-2,Н
8,2,3,Неизвестен,unknown,-1,-0.01,25,Б,Н,0,...,0,1,Б,Б,draw,Н,К,win,1,Б
9,2,4,Неизвестен,unknown,-1,-0.01,25,Б,К,1,...,0,0,Б,Н,win,Б,Б,draw,2,Н
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1196,188,3,Дальний Тайник,<=5,3,0.75,100,Н,К,0,...,1,1,Б,Б,draw,Б,К,lose,-1,К
1197,188,4,Дальний Тайник,<=5,3,0.75,100,К,Н,0,...,1,0,Н,К,win,Б,Б,draw,0,Н
1198,188,5,Дальний Тайник,<=5,3,0.75,100,Н,Н,1,...,2,0,К,Н,lose,Н,К,win,-1,Б
1199,188,6,Дальний Тайник,<=5,3,0.75,100,Б,Б,1,...,2,1,Н,Н,draw,К,Н,lose,-1,Н
1203,189,3,Дальний Тайник,<=5,4,0.80,50,К,К,1,...,2,0,К,Н,lose,Н,Б,lose,-2,Б

In [6]:
drop_features = ["match_id", "player_name","round"]
cat_features = ["win_category", "stake", "my_move", "outcome", "prev_opp_move", "prev_outcome", "prev2_opp_move", "prev2_outcome", "opp_move"]
num_features = ["opp_match_wins", "opp_match_winrate", "score_me_before", "score_opp_before", "streak_draws", "score_diff"]

In [7]:
def clean_column_names(df):
    df.columns = [re.sub(r'[\[\]<>]', '_', col) for col in df.columns]
    return df

low_cardinality = []   
high_cardinality = []       

for col in cat_features:
    n_unique = X_train[col].nunique()
    if n_unique <= 10:
        low_cardinality.append(col)
    else:
        high_cardinality.append(col)

imputer_scaler_encoder = ColumnTransformer(
    transformers = [
        ('drop_features', 'drop', drop_features),
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', RobustScaler())
        ]), num_features),
        
        ('low_cat', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ]), low_cardinality),
        
        ('high_cat', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', TargetEncoder(smooth=10))
        ]), high_cardinality)
    ],
    verbose_feature_names_out=False,
    remainder='drop'
)

preprocessor = Pipeline(
    [
        ('imputer_scaler_encoder', imputer_scaler_encoder),
        ('cleaner', FunctionTransformer(clean_column_names))
    ]
)

In [8]:
results = {
    'train_acc': [],
    'valid_acc': [],
    # 'train_roc_auc': [],
    # 'valid_roc_auc': [],
}
KFoldMean = {
    'mean_acc': [],
    # 'mean_roc_auc': [],
}

index_name = []

def resultTrainValid():
    results_df = pd.DataFrame(
        results,
        index_name
    )
    return results_df

def resultKFoldMean():
    results_KFoldMean = pd.DataFrame(
    KFoldMean,
    index_name
    )
    return results_KFoldMean


def fit_and_add(pipeline, x = X_train, y = y_train):
    pipeline.fit(x, y)
    train_acc_score = accuracy_score(y, pipeline.predict(x))
    valid_acc_score = accuracy_score(y_valid, pipeline.predict(X_valid))
    results['train_acc'].append(train_acc_score)
    results['valid_acc'].append(valid_acc_score)
    # train_roc_auc_score = roc_auc_score(y, pipeline.predict_proba(x)[:, 1])
    # valid_roc_auc_score = roc_auc_score(y_valid, pipeline.predict_proba(X_valid)[:, 1])
    # results['train_roc_auc'].append(train_roc_auc_score)
    # results['valid_roc_auc'].append(valid_roc_auc_score)


def fit_and_add_and_KFoldmean3_for_boost(pipeline, name):
    index_name.append(name)
    train_acc_score = accuracy_score(y_train, pipeline.predict(preprocessor.transform(X_train)))
    valid_acc_score = accuracy_score(y_valid, pipeline.predict(preprocessor.transform(X_valid)))
    results['train_acc'].append(train_acc_score)
    results['valid_acc'].append(valid_acc_score)
    # train_roc_auc_score = roc_auc_score(y_train, pipeline.predict_proba(preprocessor.transform(X_train))[:, 1])
    # valid_roc_auc_score = roc_auc_score(y_valid, pipeline.predict_proba(preprocessor.transform(X_valid))[:, 1])
    # results['train_roc_auc'].append(train_roc_auc_score)
    # results['valid_roc_auc'].append(valid_roc_auc_score)
    cv = KFold(n_splits=3, random_state=42, shuffle=True)
    
    full_pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('model', pipeline.__class__(**{k:v for k,v in pipeline.get_params().items() 
                                      if k != 'early_stopping_rounds'}))
    ])
    
    cross_acc = cross_val_score(full_pipeline, X, y, cv = cv, scoring='accuracy')
    KFoldMean['mean_acc'].append(cross_acc.mean())
    # cross_roc_auc = cross_val_score(full_pipeline, X, y, cv = cv, scoring='roc_auc')
    # KFoldMean['mean_roc_auc'].append(cross_roc_auc.mean())


def KFoldmean3(pipeline):
    cv = KFold(n_splits=5, random_state=42, shuffle=True)
    
    cross_acc_validation_result = cross_val_score(pipeline, X, y, cv = cv, scoring='accuracy')
    KFoldMean['mean_acc'].append(cross_acc_validation_result.mean())
    # cross_roc_auc_validation_result = cross_val_score(pipeline, X, y, cv = cv, scoring='roc_auc')
    # KFoldMean['mean_roc_auc'].append(cross_roc_auc_validation_result.mean())
    

def create_pipeline(model, name):
    index_name.append(name)
    pipeline = Pipeline(
    [
        ('preprocessor', preprocessor),
        ('model', model)
    ]
    )
    fit_and_add(pipeline)
    KFoldmean3(pipeline)

def create_tree_pipeline_with_rf(name):
    rf = RandomForestClassifier(n_estimators=160, max_depth=8, min_samples_split=3, min_samples_leaf=1, max_features = 'sqrt', random_state=42)
    create_pipeline(rf, name)

In [9]:
preprocessor.fit(X_train, y_train)
preprocessed_X_train = preprocessor.transform(X_train)
preprocessed_X_valid = preprocessor.transform(X_valid)

In [10]:
lr = LogisticRegression(solver = 'saga', C = 15.632429914797136, max_iter = 2688, penalty='elasticnet', l1_ratio = 0.13128978495943688)
knn = KNeighborsClassifier(n_neighbors=18, p=1, weights='distance')
tree_pipeline = DecisionTreeClassifier(max_depth=4, criterion='entropy', min_samples_split=4, min_samples_leaf = 6, random_state=42)

In [11]:
create_pipeline(lr, 'LogReg')
create_pipeline(knn, 'KNN')
create_pipeline(tree_pipeline, 'Tree')
create_tree_pipeline_with_rf('Tree with rf')

f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\Games\КНБ\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [20]:
cb1 = CatBoostClassifier(
    iterations=500,
    learning_rate=0.07124576882391896,
    depth=3,
    l2_leaf_reg=0.21299532752549347,
    random_strength=0.015967641801089134,
    colsample_bylevel = 0.9615823541984749,
    border_count=240,
    eval_metric='Accuracy',
    min_data_in_leaf = 6
)

cb1.fit(
    preprocessed_X_train,
    y_train,
    eval_set=(preprocessed_X_valid, y_valid),
    # plot=True
)

fit_and_add_and_KFoldmean3_for_boost(cb1, 'CatBoostClassifier1')

0:	learn: 0.4411765	test: 0.3125000	best: 0.3125000 (0)	total: 652us	remaining: 326ms
1:	learn: 0.4352941	test: 0.3281250	best: 0.3281250 (1)	total: 1.15ms	remaining: 286ms
2:	learn: 0.4666667	test: 0.3593750	best: 0.3593750 (2)	total: 1.63ms	remaining: 269ms
3:	learn: 0.4784314	test: 0.3281250	best: 0.3593750 (2)	total: 2.09ms	remaining: 259ms
4:	learn: 0.4686275	test: 0.3203125	best: 0.3593750 (2)	total: 2.53ms	remaining: 251ms
5:	learn: 0.4843137	test: 0.3437500	best: 0.3593750 (2)	total: 2.98ms	remaining: 245ms
6:	learn: 0.4784314	test: 0.3515625	best: 0.3593750 (2)	total: 3.42ms	remaining: 241ms
7:	learn: 0.4784314	test: 0.3515625	best: 0.3593750 (2)	total: 4.02ms	remaining: 247ms
8:	learn: 0.4764706	test: 0.3515625	best: 0.3593750 (2)	total: 4.49ms	remaining: 245ms
9:	learn: 0.4882353	test: 0.3671875	best: 0.3671875 (9)	total: 4.92ms	remaining: 241ms
10:	learn: 0.4921569	test: 0.3750000	best: 0.3750000 (10)	total: 5.36ms	remaining: 238ms
11:	learn: 0.4745098	test: 0.3437500	best: 0.3750000 (10)	total: 5.82ms	remaining: 237ms
12:	learn: 0.4882353	test: 0.3281250	best: 0.3750000 (10)	total: 6.26ms	remaining: 235ms
13:	learn: 0.4843137	test: 0.3671875	best: 0.3750000 (10)	total: 6.72ms	remaining: 233ms
14:	learn: 0.4745098	test: 0.3750000	best: 0.3750000 (10)	total: 7.16ms	remaining: 232ms
15:	learn: 0.4843137	test: 0.3750000	best: 0.3750000 (10)	total: 7.67ms	remaining: 232ms
16:	learn: 0.4921569	test: 0.3515625	best: 0.3750000 (10)	total: 8.14ms	remaining: 231ms
17:	learn: 0.5019608	test: 0.3593750	best: 0.3750000 (10)	total: 8.59ms	remaining: 230ms
18:	learn: 0.5058824	test: 0.3593750	best: 0.3750000 (10)	total: 9.03ms	remaining: 229ms
19:	learn: 0.5000000	test: 0.3671875	best: 0.3750000 (10)	total: 9.48ms	remaining: 227ms
20:	learn: 0.4980392	test: 0.3750000	best: 0.3750000 (10)	total: 9.91ms	remaining: 226ms
21:	learn: 0.5019608	test: 0.3750000	best: 0.3750000 (10)	total: 10.4ms	remaining: 225ms
22:	learn: 0.4941176	test: 0.3593750	best: 0.3750000 (10)	total: 10.8ms	remaining: 224ms
23:	learn: 0.4960784	test: 0.3671875	best: 0.3750000 (10)	total: 11.3ms	remaining: 224ms
24:	learn: 0.5019608	test: 0.3828125	best: 0.3828125 (24)	total: 11.8ms	remaining: 223ms
25:	learn: 0.5098039	test: 0.3671875	best: 0.3828125 (24)	total: 12.2ms	remaining: 223ms
26:	learn: 0.5294118	test: 0.3671875	best: 0.3828125 (24)	total: 12.7ms	remaining: 222ms
27:	learn: 0.5235294	test: 0.3750000	best: 0.3828125 (24)	total: 13.1ms	remaining: 221ms
28:	learn: 0.5254902	test: 0.3671875	best: 0.3828125 (24)	total: 13.6ms	remaining: 220ms
29:	learn: 0.5372549	test: 0.3750000	best: 0.3828125 (24)	total: 14ms	remaining: 219ms
30:	learn: 0.5372549	test: 0.3671875	best: 0.3828125 (24)	total: 14.5ms	remaining: 219ms
31:	learn: 0.5352941	test: 0.3828125	best: 0.3828125 (24)	total: 14.9ms	remaining: 218ms
32:	learn: 0.5431373	test: 0.3750000	best: 0.3828125 (24)	total: 15.4ms	remaining: 217ms
33:	learn: 0.5411765	test: 0.3671875	best: 0.3828125 (24)	total: 15.8ms	remaining: 217ms
34:	learn: 0.5490196	test: 0.3750000	best: 0.3828125 (24)	total: 16.3ms	remaining: 216ms
35:	learn: 0.5509804	test: 0.3750000	best: 0.3828125 (24)	total: 16.9ms	remaining: 218ms
36:	learn: 0.5588235	test: 0.3750000	best: 0.3828125 (24)	total: 17.4ms	remaining: 218ms
37:	learn: 0.5588235	test: 0.3750000	best: 0.3828125 (24)	total: 17.9ms	remaining: 218ms
38:	learn: 0.5549020	test: 0.3671875	best: 0.3828125 (24)	total: 18.4ms	remaining: 218ms
39:	learn: 0.5490196	test: 0.3750000	best: 0.3828125 (24)	total: 18.8ms	remaining: 217ms
40:	learn: 0.5529412	test: 0.3750000	best: 0.3828125 (24)	total: 19.3ms	remaining: 216ms
41:	learn: 0.5588235	test: 0.3906250	best: 0.3906250 (41)	total: 19.8ms	remaining: 215ms
42:	learn: 0.5627451	test: 0.3984375	best: 0.3984375 (42)	total: 20.2ms	remaining: 215ms
43:	learn: 0.5647059	test: 0.3906250	best: 0.3984375 (42)	total: 20.6ms	remaining: 214ms
44:	learn: 0.5666667	test: 0.4140625	best: 0.4140625 (44)	total: 21.1ms	remaining: 213ms
45:	learn: 0.5745098	test: 0.4062500	best: 0.4140625 (44)	total: 21.7ms	remaining: 214ms
46:	learn: 0.5686275	test: 0.4062500	best: 0.4140625 (44)	total: 22.1ms	remaining: 213ms
47:	learn: 0.5764706	test: 0.3984375	best: 0.4140625 (44)	total: 22.6ms	remaining: 212ms
48:	learn: 0.5823529	test: 0.3750000	best: 0.4140625 (44)	total: 23ms	remaining: 212ms
49:	learn: 0.5725490	test: 0.3671875	best: 0.4140625 (44)	total: 23.4ms	remaining: 211ms
50:	learn: 0.5862745	test: 0.3671875	best: 0.4140625 (44)	total: 23.9ms	remaining: 210ms
51:	learn: 0.5901961	test: 0.3750000	best: 0.4140625 (44)	total: 24.4ms	remaining: 210ms
52:	learn: 0.5980392	test: 0.3906250	best: 0.4140625 (44)	total: 24.8ms	remaining: 209ms
53:	learn: 0.5980392	test: 0.3671875	best: 0.4140625 (44)	total: 25.3ms	remaining: 209ms
54:	learn: 0.6039216	test: 0.3750000	best: 0.4140625 (44)	total: 25.8ms	remaining: 209ms
55:	learn: 0.6019608	test: 0.3828125	best: 0.4140625 (44)	total: 26.3ms	remaining: 208ms
56:	learn: 0.6019608	test: 0.3750000	best: 0.4140625 (44)	total: 26.7ms	remaining: 208ms
57:	learn: 0.6019608	test: 0.3750000	best: 0.4140625 (44)	total: 27.2ms	remaining: 207ms
58:	learn: 0.6000000	test: 0.3750000	best: 0.4140625 (44)	total: 27.6ms	remaining: 206ms
59:	learn: 0.6039216	test: 0.3750000	best: 0.4140625 (44)	total: 28.1ms	remaining: 206ms
60:	learn: 0.6078431	test: 0.3671875	best: 0.4140625 (44)	total: 28.5ms	remaining: 205ms
61:	learn: 0.6098039	test: 0.3515625	best: 0.4140625 (44)	total: 29ms	remaining: 205ms
62:	learn: 0.6039216	test: 0.3593750	best: 0.4140625 (44)	total: 29.4ms	remaining: 204ms
63:	learn: 0.6078431	test: 0.3359375	best: 0.4140625 (44)	total: 30ms	remaining: 204ms
64:	learn: 0.6058824	test: 0.3437500	best: 0.4140625 (44)	total: 30.5ms	remaining: 204ms
65:	learn: 0.6098039	test: 0.3359375	best: 0.4140625 (44)	total: 31ms	remaining: 204ms
66:	learn: 0.6137255	test: 0.3437500	best: 0.4140625 (44)	total: 31.5ms	remaining: 203ms
67:	learn: 0.6078431	test: 0.3437500	best: 0.4140625 (44)	total: 31.9ms	remaining: 203ms
68:	learn: 0.6078431	test: 0.3437500	best: 0.4140625 (44)	total: 32.5ms	remaining: 203ms
69:	learn: 0.6098039	test: 0.3437500	best: 0.4140625 (44)	total: 33ms	remaining: 203ms
70:	learn: 0.6078431	test: 0.3593750	best: 0.4140625 (44)	total: 33.5ms	remaining: 202ms
71:	learn: 0.6098039	test: 0.3671875	best: 0.4140625 (44)	total: 33.9ms	remaining: 202ms
72:	learn: 0.6156863	test: 0.3437500	best: 0.4140625 (44)	total: 34.4ms	remaining: 201ms
73:	learn: 0.6137255	test: 0.3437500	best: 0.4140625 (44)	total: 35ms	remaining: 201ms
74:	learn: 0.6078431	test: 0.3593750	best: 0.4140625 (44)	total: 35.8ms	remaining: 203ms
75:	learn: 0.6156863	test: 0.3593750	best: 0.4140625 (44)	total: 36.4ms	remaining: 203ms
76:	learn: 0.6156863	test: 0.3671875	best: 0.4140625 (44)	total: 36.9ms	remaining: 203ms
77:	learn: 0.6196078	test: 0.3593750	best: 0.4140625 (44)	total: 37.4ms	remaining: 202ms
78:	learn: 0.6176471	test: 0.3437500	best: 0.4140625 (44)	total: 37.9ms	remaining: 202ms
79:	learn: 0.6196078	test: 0.3281250	best: 0.4140625 (44)	total: 38.7ms	remaining: 203ms
80:	learn: 0.6176471	test: 0.3437500	best: 0.4140625 (44)	total: 39.3ms	remaining: 203ms
81:	learn: 0.6137255	test: 0.3359375	best: 0.4140625 (44)	total: 40.1ms	remaining: 204ms
82:	learn: 0.6176471	test: 0.3281250	best: 0.4140625 (44)	total: 40.6ms	remaining: 204ms
83:	learn: 0.6215686	test: 0.3281250	best: 0.4140625 (44)	total: 41ms	remaining: 203ms
84:	learn: 0.6215686	test: 0.3281250	best: 0.4140625 (44)	total: 41.5ms	remaining: 203ms
85:	learn: 0.6294118	test: 0.3437500	best: 0.4140625 (44)	total: 41.9ms	remaining: 202ms
86:	learn: 0.6274510	test: 0.3359375	best: 0.4140625 (44)	total: 42.4ms	remaining: 201ms
87:	learn: 0.6235294	test: 0.3359375	best: 0.4140625 (44)	total: 42.9ms	remaining: 201ms
88:	learn: 0.6235294	test: 0.3359375	best: 0.4140625 (44)	total: 43.5ms	remaining: 201ms
89:	learn: 0.6274510	test: 0.3359375	best: 0.4140625 (44)	total: 43.9ms	remaining: 200ms
90:	learn: 0.6333333	test: 0.3359375	best: 0.4140625 (44)	total: 44.4ms	remaining: 200ms
91:	learn: 0.6352941	test: 0.3359375	best: 0.4140625 (44)	total: 44.9ms	remaining: 199ms
92:	learn: 0.6313725	test: 0.3359375	best: 0.4140625 (44)	total: 45.3ms	remaining: 198ms
93:	learn: 0.6254902	test: 0.3515625	best: 0.4140625 (44)	total: 45.8ms	remaining: 198ms
94:	learn: 0.6333333	test: 0.3437500	best: 0.4140625 (44)	total: 46.3ms	remaining: 197ms
95:	learn: 0.6372549	test: 0.3437500	best: 0.4140625 (44)	total: 46.8ms	remaining: 197ms
96:	learn: 0.6294118	test: 0.3359375	best: 0.4140625 (44)	total: 47.2ms	remaining: 196ms
97:	learn: 0.6313725	test: 0.3437500	best: 0.4140625 (44)	total: 47.7ms	remaining: 196ms
98:	learn: 0.6274510	test: 0.3359375	best: 0.4140625 (44)	total: 48.2ms	remaining: 195ms
99:	learn: 0.6352941	test: 0.3437500	best: 0.4140625 (44)	total: 48.6ms	remaining: 194ms
100:	learn: 0.6352941	test: 0.3437500	best: 0.4140625 (44)	total: 49.1ms	remaining: 194ms
101:	learn: 0.6352941	test: 0.3437500	best: 0.4140625 (44)	total: 49.5ms	remaining: 193ms
102:	learn: 0.6333333	test: 0.3437500	best: 0.4140625 (44)	total: 50ms	remaining: 193ms
103:	learn: 0.6392157	test: 0.3437500	best: 0.4140625 (44)	total: 50.5ms	remaining: 192ms
104:	learn: 0.6352941	test: 0.3437500	best: 0.4140625 (44)	total: 50.9ms	remaining: 192ms
105:	learn: 0.6372549	test: 0.3515625	best: 0.4140625 (44)	total: 51.4ms	remaining: 191ms
106:	learn: 0.6411765	test: 0.3593750	best: 0.4140625 (44)	total: 51.8ms	remaining: 190ms
107:	learn: 0.6450980	test: 0.3593750	best: 0.4140625 (44)	total: 52.3ms	remaining: 190ms
108:	learn: 0.6431373	test: 0.3515625	best: 0.4140625 (44)	total: 52.7ms	remaining: 189ms
109:	learn: 0.6470588	test: 0.3359375	best: 0.4140625 (44)	total: 53.2ms	remaining: 189ms
110:	learn: 0.6509804	test: 0.3359375	best: 0.4140625 (44)	total: 53.7ms	remaining: 188ms
111:	learn: 0.6529412	test: 0.3203125	best: 0.4140625 (44)	total: 54.1ms	remaining: 188ms
112:	learn: 0.6549020	test: 0.3125000	best: 0.4140625 (44)	total: 54.6ms	remaining: 187ms
113:	learn: 0.6529412	test: 0.3281250	best: 0.4140625 (44)	total: 55ms	remaining: 186ms
114:	learn: 0.6509804	test: 0.3359375	best: 0.4140625 (44)	total: 55.5ms	remaining: 186ms
115:	learn: 0.6549020	test: 0.3515625	best: 0.4140625 (44)	total: 55.9ms	remaining: 185ms
116:	learn: 0.6568627	test: 0.3359375	best: 0.4140625 (44)	total: 56.4ms	remaining: 185ms
117:	learn: 0.6588235	test: 0.3359375	best: 0.4140625 (44)	total: 56.9ms	remaining: 184ms
118:	learn: 0.6568627	test: 0.3515625	best: 0.4140625 (44)	total: 57.4ms	remaining: 184ms
119:	learn: 0.6549020	test: 0.3593750	best: 0.4140625 (44)	total: 57.8ms	remaining: 183ms
120:	learn: 0.6568627	test: 0.3515625	best: 0.4140625 (44)	total: 58.3ms	remaining: 183ms
121:	learn: 0.6647059	test: 0.3515625	best: 0.4140625 (44)	total: 58.7ms	remaining: 182ms
122:	learn: 0.6627451	test: 0.3515625	best: 0.4140625 (44)	total: 59.2ms	remaining: 181ms
123:	learn: 0.6627451	test: 0.3515625	best: 0.4140625 (44)	total: 59.6ms	remaining: 181ms
124:	learn: 0.6568627	test: 0.3437500	best: 0.4140625 (44)	total: 60.1ms	remaining: 180ms
125:	learn: 0.6549020	test: 0.3437500	best: 0.4140625 (44)	total: 60.5ms	remaining: 180ms
126:	learn: 0.6588235	test: 0.3515625	best: 0.4140625 (44)	total: 61ms	remaining: 179ms
127:	learn: 0.6607843	test: 0.3593750	best: 0.4140625 (44)	total: 61.4ms	remaining: 179ms
128:	learn: 0.6588235	test: 0.3671875	best: 0.4140625 (44)	total: 61.9ms	remaining: 178ms
129:	learn: 0.6549020	test: 0.3593750	best: 0.4140625 (44)	total: 62.3ms	remaining: 177ms
130:	learn: 0.6568627	test: 0.3437500	best: 0.4140625 (44)	total: 63ms	remaining: 177ms
131:	learn: 0.6568627	test: 0.3437500	best: 0.4140625 (44)	total: 63.5ms	remaining: 177ms
132:	learn: 0.6568627	test: 0.3515625	best: 0.4140625 (44)	total: 64.1ms	remaining: 177ms
133:	learn: 0.6607843	test: 0.3359375	best: 0.4140625 (44)	total: 64.6ms	remaining: 176ms
134:	learn: 0.6666667	test: 0.3125000	best: 0.4140625 (44)	total: 65ms	remaining: 176ms
135:	learn: 0.6686275	test: 0.3203125	best: 0.4140625 (44)	total: 65.4ms	remaining: 175ms
136:	learn: 0.6725490	test: 0.3203125	best: 0.4140625 (44)	total: 65.9ms	remaining: 175ms
137:	learn: 0.6705882	test: 0.3203125	best: 0.4140625 (44)	total: 66.3ms	remaining: 174ms
138:	learn: 0.6705882	test: 0.3359375	best: 0.4140625 (44)	total: 66.8ms	remaining: 173ms
139:	learn: 0.6725490	test: 0.3281250	best: 0.4140625 (44)	total: 67.2ms	remaining: 173ms
140:	learn: 0.6725490	test: 0.3203125	best: 0.4140625 (44)	total: 67.7ms	remaining: 172ms
141:	learn: 0.6705882	test: 0.3281250	best: 0.4140625 (44)	total: 68.2ms	remaining: 172ms
142:	learn: 0.6705882	test: 0.3203125	best: 0.4140625 (44)	total: 68.7ms	remaining: 171ms
143:	learn: 0.6745098	test: 0.3203125	best: 0.4140625 (44)	total: 69.1ms	remaining: 171ms
144:	learn: 0.6705882	test: 0.3359375	best: 0.4140625 (44)	total: 69.6ms	remaining: 170ms
145:	learn: 0.6725490	test: 0.3437500	best: 0.4140625 (44)	total: 70ms	remaining: 170ms
146:	learn: 0.6686275	test: 0.3281250	best: 0.4140625 (44)	total: 70.5ms	remaining: 169ms
147:	learn: 0.6745098	test: 0.3281250	best: 0.4140625 (44)	total: 71ms	remaining: 169ms
148:	learn: 0.6705882	test: 0.3281250	best: 0.4140625 (44)	total: 71.4ms	remaining: 168ms
149:	learn: 0.6705882	test: 0.3281250	best: 0.4140625 (44)	total: 71.9ms	remaining: 168ms
150:	learn: 0.6784314	test: 0.3203125	best: 0.4140625 (44)	total: 72.3ms	remaining: 167ms
151:	learn: 0.6803922	test: 0.3437500	best: 0.4140625 (44)	total: 72.8ms	remaining: 167ms
152:	learn: 0.6764706	test: 0.3359375	best: 0.4140625 (44)	total: 73.2ms	remaining: 166ms
153:	learn: 0.6745098	test: 0.3359375	best: 0.4140625 (44)	total: 73.7ms	remaining: 165ms
154:	learn: 0.6764706	test: 0.3437500	best: 0.4140625 (44)	total: 74.1ms	remaining: 165ms
155:	learn: 0.6745098	test: 0.3281250	best: 0.4140625 (44)	total: 74.6ms	remaining: 164ms
156:	learn: 0.6764706	test: 0.3281250	best: 0.4140625 (44)	total: 75.2ms	remaining: 164ms
157:	learn: 0.6745098	test: 0.3281250	best: 0.4140625 (44)	total: 75.7ms	remaining: 164ms
158:	learn: 0.6784314	test: 0.3281250	best: 0.4140625 (44)	total: 76.2ms	remaining: 163ms
159:	learn: 0.6784314	test: 0.3281250	best: 0.4140625 (44)	total: 76.7ms	remaining: 163ms
160:	learn: 0.6784314	test: 0.3281250	best: 0.4140625 (44)	total: 77.2ms	remaining: 163ms
161:	learn: 0.6843137	test: 0.3437500	best: 0.4140625 (44)	total: 77.6ms	remaining: 162ms
162:	learn: 0.6901961	test: 0.3437500	best: 0.4140625 (44)	total: 78.2ms	remaining: 162ms
163:	learn: 0.6921569	test: 0.3359375	best: 0.4140625 (44)	total: 78.7ms	remaining: 161ms
164:	learn: 0.6921569	test: 0.3437500	best: 0.4140625 (44)	total: 79.3ms	remaining: 161ms
165:	learn: 0.6960784	test: 0.3437500	best: 0.4140625 (44)	total: 79.8ms	remaining: 160ms
166:	learn: 0.6941176	test: 0.3437500	best: 0.4140625 (44)	total: 80.2ms	remaining: 160ms
167:	learn: 0.6980392	test: 0.3437500	best: 0.4140625 (44)	total: 80.7ms	remaining: 159ms
168:	learn: 0.6980392	test: 0.3437500	best: 0.4140625 (44)	total: 81.2ms	remaining: 159ms
169:	learn: 0.7000000	test: 0.3281250	best: 0.4140625 (44)	total: 81.8ms	remaining: 159ms
170:	learn: 0.7000000	test: 0.3281250	best: 0.4140625 (44)	total: 82.3ms	remaining: 158ms
171:	learn: 0.7019608	test: 0.3281250	best: 0.4140625 (44)	total: 82.8ms	remaining: 158ms
172:	learn: 0.7078431	test: 0.3281250	best: 0.4140625 (44)	total: 83.3ms	remaining: 157ms
173:	learn: 0.7058824	test: 0.3281250	best: 0.4140625 (44)	total: 83.7ms	remaining: 157ms
174:	learn: 0.7039216	test: 0.3281250	best: 0.4140625 (44)	total: 84.2ms	remaining: 156ms
175:	learn: 0.7019608	test: 0.3203125	best: 0.4140625 (44)	total: 84.6ms	remaining: 156ms
176:	learn: 0.7058824	test: 0.3359375	best: 0.4140625 (44)	total: 85.2ms	remaining: 156ms
177:	learn: 0.7117647	test: 0.3359375	best: 0.4140625 (44)	total: 85.8ms	remaining: 155ms
178:	learn: 0.7117647	test: 0.3359375	best: 0.4140625 (44)	total: 86.3ms	remaining: 155ms
179:	learn: 0.7117647	test: 0.3437500	best: 0.4140625 (44)	total: 86.8ms	remaining: 154ms
180:	learn: 0.7117647	test: 0.3593750	best: 0.4140625 (44)	total: 87.3ms	remaining: 154ms
181:	learn: 0.7117647	test: 0.3515625	best: 0.4140625 (44)	total: 87.8ms	remaining: 153ms
182:	learn: 0.7137255	test: 0.3437500	best: 0.4140625 (44)	total: 88.2ms	remaining: 153ms
183:	learn: 0.7137255	test: 0.3437500	best: 0.4140625 (44)	total: 88.7ms	remaining: 152ms
184:	learn: 0.7078431	test: 0.3437500	best: 0.4140625 (44)	total: 89.2ms	remaining: 152ms
185:	learn: 0.7117647	test: 0.3281250	best: 0.4140625 (44)	total: 89.7ms	remaining: 151ms
186:	learn: 0.7117647	test: 0.3281250	best: 0.4140625 (44)	total: 90.2ms	remaining: 151ms
187:	learn: 0.7137255	test: 0.3281250	best: 0.4140625 (44)	total: 90.7ms	remaining: 151ms
188:	learn: 0.7137255	test: 0.3281250	best: 0.4140625 (44)	total: 91.2ms	remaining: 150ms
189:	learn: 0.7137255	test: 0.3359375	best: 0.4140625 (44)	total: 91.7ms	remaining: 150ms
190:	learn: 0.7156863	test: 0.3281250	best: 0.4140625 (44)	total: 92.2ms	remaining: 149ms
191:	learn: 0.7137255	test: 0.3359375	best: 0.4140625 (44)	total: 92.8ms	remaining: 149ms
192:	learn: 0.7098039	test: 0.3437500	best: 0.4140625 (44)	total: 93.3ms	remaining: 148ms
193:	learn: 0.7117647	test: 0.3437500	best: 0.4140625 (44)	total: 94.2ms	remaining: 149ms
194:	learn: 0.7137255	test: 0.3281250	best: 0.4140625 (44)	total: 94.8ms	remaining: 148ms
195:	learn: 0.7117647	test: 0.3281250	best: 0.4140625 (44)	total: 95.3ms	remaining: 148ms
196:	learn: 0.7117647	test: 0.3281250	best: 0.4140625 (44)	total: 95.9ms	remaining: 147ms
197:	learn: 0.7156863	test: 0.3359375	best: 0.4140625 (44)	total: 96.4ms	remaining: 147ms
198:	learn: 0.7156863	test: 0.3281250	best: 0.4140625 (44)	total: 96.9ms	remaining: 147ms
199:	learn: 0.7176471	test: 0.3359375	best: 0.4140625 (44)	total: 97.6ms	remaining: 146ms
200:	learn: 0.7176471	test: 0.3203125	best: 0.4140625 (44)	total: 98.3ms	remaining: 146ms
201:	learn: 0.7176471	test: 0.3437500	best: 0.4140625 (44)	total: 98.9ms	remaining: 146ms
202:	learn: 0.7215686	test: 0.3437500	best: 0.4140625 (44)	total: 99.6ms	remaining: 146ms
203:	learn: 0.7215686	test: 0.3359375	best: 0.4140625 (44)	total: 100ms	remaining: 145ms
204:	learn: 0.7215686	test: 0.3359375	best: 0.4140625 (44)	total: 101ms	remaining: 145ms
205:	learn: 0.7254902	test: 0.3281250	best: 0.4140625 (44)	total: 101ms	remaining: 144ms
206:	learn: 0.7294118	test: 0.3281250	best: 0.4140625 (44)	total: 102ms	remaining: 144ms
207:	learn: 0.7254902	test: 0.3359375	best: 0.4140625 (44)	total: 102ms	remaining: 143ms
208:	learn: 0.7294118	test: 0.3359375	best: 0.4140625 (44)	total: 103ms	remaining: 143ms
209:	learn: 0.7254902	test: 0.3359375	best: 0.4140625 (44)	total: 103ms	remaining: 143ms
210:	learn: 0.7313725	test: 0.3437500	best: 0.4140625 (44)	total: 104ms	remaining: 142ms
211:	learn: 0.7372549	test: 0.3437500	best: 0.4140625 (44)	total: 104ms	remaining: 142ms
212:	learn: 0.7352941	test: 0.3437500	best: 0.4140625 (44)	total: 105ms	remaining: 142ms
213:	learn: 0.7333333	test: 0.3437500	best: 0.4140625 (44)	total: 106ms	remaining: 142ms
214:	learn: 0.7372549	test: 0.3437500	best: 0.4140625 (44)	total: 107ms	remaining: 141ms
215:	learn: 0.7352941	test: 0.3437500	best: 0.4140625 (44)	total: 107ms	remaining: 141ms
216:	learn: 0.7392157	test: 0.3437500	best: 0.4140625 (44)	total: 108ms	remaining: 141ms
217:	learn: 0.7352941	test: 0.3515625	best: 0.4140625 (44)	total: 108ms	remaining: 140ms
218:	learn: 0.7372549	test: 0.3515625	best: 0.4140625 (44)	total: 109ms	remaining: 140ms
219:	learn: 0.7392157	test: 0.3437500	best: 0.4140625 (44)	total: 114ms	remaining: 145ms
220:	learn: 0.7411765	test: 0.3437500	best: 0.4140625 (44)	total: 115ms	remaining: 145ms
221:	learn: 0.7470588	test: 0.3359375	best: 0.4140625 (44)	total: 115ms	remaining: 144ms
222:	learn: 0.7470588	test: 0.3359375	best: 0.4140625 (44)	total: 116ms	remaining: 144ms
223:	learn: 0.7431373	test: 0.3437500	best: 0.4140625 (44)	total: 116ms	remaining: 143ms

In [21]:
cb2 = CatBoostClassifier(
    iterations=750,
    learning_rate=0.08564718921836138,
    depth=3,
    l2_leaf_reg=0.35913779146836167,
    bootstrap_type='Bernoulli',
    subsample=0.9779265440256093,
    random_strength=0.015967641801089134,
    border_count=32,
    eval_metric='Accuracy'
)

cb2.fit(
    preprocessed_X_train,
    y_train,
    eval_set=(preprocessed_X_valid, y_valid),
    # plot=True
)

fit_and_add_and_KFoldmean3_for_boost(cb2, 'CatBoostClassifier2')

0:	learn: 0.4450980	test: 0.4453125	best: 0.4453125 (0)	total: 655us	remaining: 491ms
1:	learn: 0.4725490	test: 0.3437500	best: 0.4453125 (0)	total: 1.2ms	remaining: 450ms
2:	learn: 0.4607843	test: 0.3359375	best: 0.4453125 (0)	total: 1.75ms	remaining: 435ms
3:	learn: 0.4666667	test: 0.3359375	best: 0.4453125 (0)	total: 2.51ms	remaining: 468ms
4:	learn: 0.4686275	test: 0.3437500	best: 0.4453125 (0)	total: 3.07ms	remaining: 458ms
5:	learn: 0.4862745	test: 0.3359375	best: 0.4453125 (0)	total: 3.64ms	remaining: 451ms
6:	learn: 0.4843137	test: 0.3437500	best: 0.4453125 (0)	total: 4.08ms	remaining: 433ms
7:	learn: 0.4803922	test: 0.3515625	best: 0.4453125 (0)	total: 4.52ms	remaining: 420ms
8:	learn: 0.4882353	test: 0.3593750	best: 0.4453125 (0)	total: 4.99ms	remaining: 411ms
9:	learn: 0.5019608	test: 0.3437500	best: 0.4453125 (0)	total: 5.42ms	remaining: 401ms
10:	learn: 0.5019608	test: 0.3281250	best: 0.4453125 (0)	total: 6.1ms	remaining: 410ms
11:	learn: 0.5000000	test: 0.3671875	best: 0.4453125 (0)	total: 6.65ms	remaining: 409ms
12:	learn: 0.5058824	test: 0.3671875	best: 0.4453125 (0)	total: 7.1ms	remaining: 403ms
13:	learn: 0.5196078	test: 0.3203125	best: 0.4453125 (0)	total: 7.56ms	remaining: 397ms
14:	learn: 0.5039216	test: 0.3281250	best: 0.4453125 (0)	total: 8.01ms	remaining: 392ms
15:	learn: 0.5156863	test: 0.3281250	best: 0.4453125 (0)	total: 8.46ms	remaining: 388ms
16:	learn: 0.5235294	test: 0.3281250	best: 0.4453125 (0)	total: 8.91ms	remaining: 384ms
17:	learn: 0.5176471	test: 0.3359375	best: 0.4453125 (0)	total: 9.39ms	remaining: 382ms
18:	learn: 0.5196078	test: 0.3515625	best: 0.4453125 (0)	total: 9.87ms	remaining: 380ms
19:	learn: 0.5176471	test: 0.3515625	best: 0.4453125 (0)	total: 10.4ms	remaining: 378ms
20:	learn: 0.5313725	test: 0.3437500	best: 0.4453125 (0)	total: 11ms	remaining: 381ms
21:	learn: 0.5313725	test: 0.3437500	best: 0.4453125 (0)	total: 11.6ms	remaining: 382ms
22:	learn: 0.5450980	test: 0.3203125	best: 0.4453125 (0)	total: 12ms	remaining: 380ms
23:	learn: 0.5490196	test: 0.3203125	best: 0.4453125 (0)	total: 12.5ms	remaining: 377ms
24:	learn: 0.5549020	test: 0.3203125	best: 0.4453125 (0)	total: 13ms	remaining: 376ms
25:	learn: 0.5686275	test: 0.3046875	best: 0.4453125 (0)	total: 13.4ms	remaining: 374ms
26:	learn: 0.5666667	test: 0.3125000	best: 0.4453125 (0)	total: 13.9ms	remaining: 372ms
27:	learn: 0.5686275	test: 0.3046875	best: 0.4453125 (0)	total: 14.3ms	remaining: 370ms
28:	learn: 0.5588235	test: 0.3203125	best: 0.4453125 (0)	total: 14.8ms	remaining: 368ms
29:	learn: 0.5588235	test: 0.3359375	best: 0.4453125 (0)	total: 15.2ms	remaining: 366ms
30:	learn: 0.5666667	test: 0.3281250	best: 0.4453125 (0)	total: 15.7ms	remaining: 364ms
31:	learn: 0.5666667	test: 0.3437500	best: 0.4453125 (0)	total: 16.3ms	remaining: 366ms
32:	learn: 0.5686275	test: 0.3437500	best: 0.4453125 (0)	total: 16.8ms	remaining: 364ms
33:	learn: 0.5803922	test: 0.3593750	best: 0.4453125 (0)	total: 17.2ms	remaining: 363ms
34:	learn: 0.5803922	test: 0.3593750	best: 0.4453125 (0)	total: 17.7ms	remaining: 361ms
35:	learn: 0.5803922	test: 0.3593750	best: 0.4453125 (0)	total: 18.1ms	remaining: 359ms
36:	learn: 0.5745098	test: 0.3515625	best: 0.4453125 (0)	total: 18.6ms	remaining: 358ms
37:	learn: 0.5764706	test: 0.3515625	best: 0.4453125 (0)	total: 19.1ms	remaining: 357ms
38:	learn: 0.5745098	test: 0.3593750	best: 0.4453125 (0)	total: 19.5ms	remaining: 355ms
39:	learn: 0.5686275	test: 0.3437500	best: 0.4453125 (0)	total: 20ms	remaining: 354ms
40:	learn: 0.5725490	test: 0.3203125	best: 0.4453125 (0)	total: 20.4ms	remaining: 353ms
41:	learn: 0.5843137	test: 0.3281250	best: 0.4453125 (0)	total: 20.9ms	remaining: 352ms
42:	learn: 0.5882353	test: 0.3203125	best: 0.4453125 (0)	total: 21.3ms	remaining: 350ms
43:	learn: 0.5941176	test: 0.3203125	best: 0.4453125 (0)	total: 21.8ms	remaining: 349ms
44:	learn: 0.6078431	test: 0.3203125	best: 0.4453125 (0)	total: 22.2ms	remaining: 348ms
45:	learn: 0.6117647	test: 0.3203125	best: 0.4453125 (0)	total: 22.7ms	remaining: 347ms
46:	learn: 0.6098039	test: 0.3203125	best: 0.4453125 (0)	total: 23.1ms	remaining: 346ms
47:	learn: 0.6156863	test: 0.3203125	best: 0.4453125 (0)	total: 23.6ms	remaining: 345ms
48:	learn: 0.6196078	test: 0.3359375	best: 0.4453125 (0)	total: 24ms	remaining: 344ms
49:	learn: 0.6176471	test: 0.3515625	best: 0.4453125 (0)	total: 24.5ms	remaining: 343ms
50:	learn: 0.6176471	test: 0.3515625	best: 0.4453125 (0)	total: 24.9ms	remaining: 342ms
51:	learn: 0.6274510	test: 0.3359375	best: 0.4453125 (0)	total: 25.4ms	remaining: 341ms
52:	learn: 0.6333333	test: 0.3515625	best: 0.4453125 (0)	total: 25.8ms	remaining: 340ms
53:	learn: 0.6333333	test: 0.3437500	best: 0.4453125 (0)	total: 26.3ms	remaining: 339ms
54:	learn: 0.6313725	test: 0.3437500	best: 0.4453125 (0)	total: 26.8ms	remaining: 338ms
55:	learn: 0.6333333	test: 0.3437500	best: 0.4453125 (0)	total: 27.2ms	remaining: 337ms
56:	learn: 0.6392157	test: 0.3359375	best: 0.4453125 (0)	total: 27.7ms	remaining: 336ms
57:	learn: 0.6333333	test: 0.3515625	best: 0.4453125 (0)	total: 28.1ms	remaining: 336ms
58:	learn: 0.6352941	test: 0.3437500	best: 0.4453125 (0)	total: 28.6ms	remaining: 335ms
59:	learn: 0.6352941	test: 0.3437500	best: 0.4453125 (0)	total: 29ms	remaining: 334ms
60:	learn: 0.6392157	test: 0.3437500	best: 0.4453125 (0)	total: 29.4ms	remaining: 333ms
61:	learn: 0.6490196	test: 0.3437500	best: 0.4453125 (0)	total: 29.9ms	remaining: 332ms
62:	learn: 0.6549020	test: 0.3437500	best: 0.4453125 (0)	total: 30.5ms	remaining: 332ms
63:	learn: 0.6529412	test: 0.3437500	best: 0.4453125 (0)	total: 30.9ms	remaining: 331ms
64:	learn: 0.6549020	test: 0.3437500	best: 0.4453125 (0)	total: 31.4ms	remaining: 331ms
65:	learn: 0.6529412	test: 0.3437500	best: 0.4453125 (0)	total: 31.9ms	remaining: 330ms
66:	learn: 0.6529412	test: 0.3437500	best: 0.4453125 (0)	total: 32.3ms	remaining: 330ms
67:	learn: 0.6450980	test: 0.3359375	best: 0.4453125 (0)	total: 32.8ms	remaining: 329ms
68:	learn: 0.6470588	test: 0.3359375	best: 0.4453125 (0)	total: 33.2ms	remaining: 328ms
69:	learn: 0.6529412	test: 0.3437500	best: 0.4453125 (0)	total: 33.7ms	remaining: 327ms
70:	learn: 0.6549020	test: 0.3437500	best: 0.4453125 (0)	total: 34.2ms	remaining: 327ms
71:	learn: 0.6549020	test: 0.3437500	best: 0.4453125 (0)	total: 34.7ms	remaining: 327ms
72:	learn: 0.6588235	test: 0.3437500	best: 0.4453125 (0)	total: 35.1ms	remaining: 326ms
73:	learn: 0.6627451	test: 0.3593750	best: 0.4453125 (0)	total: 35.6ms	remaining: 325ms
74:	learn: 0.6627451	test: 0.3828125	best: 0.4453125 (0)	total: 36.1ms	remaining: 325ms
75:	learn: 0.6627451	test: 0.3828125	best: 0.4453125 (0)	total: 36.5ms	remaining: 324ms
76:	learn: 0.6627451	test: 0.3906250	best: 0.4453125 (0)	total: 36.9ms	remaining: 323ms
77:	learn: 0.6627451	test: 0.3906250	best: 0.4453125 (0)	total: 37.5ms	remaining: 323ms
78:	learn: 0.6666667	test: 0.3906250	best: 0.4453125 (0)	total: 38ms	remaining: 323ms
79:	learn: 0.6686275	test: 0.3750000	best: 0.4453125 (0)	total: 38.4ms	remaining: 322ms
80:	learn: 0.6686275	test: 0.3671875	best: 0.4453125 (0)	total: 38.9ms	remaining: 321ms
81:	learn: 0.6686275	test: 0.3750000	best: 0.4453125 (0)	total: 39.3ms	remaining: 320ms
82:	learn: 0.6686275	test: 0.3750000	best: 0.4453125 (0)	total: 39.8ms	remaining: 320ms
83:	learn: 0.6725490	test: 0.3828125	best: 0.4453125 (0)	total: 40.2ms	remaining: 319ms
84:	learn: 0.6705882	test: 0.3828125	best: 0.4453125 (0)	total: 40.7ms	remaining: 318ms
85:	learn: 0.6745098	test: 0.3828125	best: 0.4453125 (0)	total: 41.2ms	remaining: 318ms
86:	learn: 0.6764706	test: 0.3750000	best: 0.4453125 (0)	total: 41.7ms	remaining: 318ms
87:	learn: 0.6823529	test: 0.3750000	best: 0.4453125 (0)	total: 42.2ms	remaining: 317ms
88:	learn: 0.6843137	test: 0.3671875	best: 0.4453125 (0)	total: 42.6ms	remaining: 316ms
89:	learn: 0.6784314	test: 0.3671875	best: 0.4453125 (0)	total: 43ms	remaining: 316ms
90:	learn: 0.6803922	test: 0.3750000	best: 0.4453125 (0)	total: 43.5ms	remaining: 315ms
91:	learn: 0.6862745	test: 0.3750000	best: 0.4453125 (0)	total: 43.9ms	remaining: 314ms
92:	learn: 0.6843137	test: 0.3671875	best: 0.4453125 (0)	total: 44.4ms	remaining: 314ms
93:	learn: 0.6843137	test: 0.3671875	best: 0.4453125 (0)	total: 44.9ms	remaining: 313ms
94:	learn: 0.6882353	test: 0.3671875	best: 0.4453125 (0)	total: 45.5ms	remaining: 313ms
95:	learn: 0.6882353	test: 0.3671875	best: 0.4453125 (0)	total: 45.9ms	remaining: 313ms
96:	learn: 0.6960784	test: 0.3828125	best: 0.4453125 (0)	total: 46.4ms	remaining: 313ms
97:	learn: 0.6901961	test: 0.3828125	best: 0.4453125 (0)	total: 46.9ms	remaining: 312ms
98:	learn: 0.6921569	test: 0.3828125	best: 0.4453125 (0)	total: 47.3ms	remaining: 311ms
99:	learn: 0.6901961	test: 0.3750000	best: 0.4453125 (0)	total: 47.8ms	remaining: 311ms
100:	learn: 0.6901961	test: 0.3750000	best: 0.4453125 (0)	total: 48.4ms	remaining: 311ms
101:	learn: 0.6901961	test: 0.3750000	best: 0.4453125 (0)	total: 48.9ms	remaining: 311ms
102:	learn: 0.6980392	test: 0.3750000	best: 0.4453125 (0)	total: 49.4ms	remaining: 310ms
103:	learn: 0.7019608	test: 0.3593750	best: 0.4453125 (0)	total: 49.9ms	remaining: 310ms
104:	learn: 0.7000000	test: 0.3593750	best: 0.4453125 (0)	total: 50.3ms	remaining: 309ms
105:	learn: 0.6980392	test: 0.3593750	best: 0.4453125 (0)	total: 50.8ms	remaining: 308ms
106:	learn: 0.6980392	test: 0.3671875	best: 0.4453125 (0)	total: 51.2ms	remaining: 308ms
107:	learn: 0.6980392	test: 0.3671875	best: 0.4453125 (0)	total: 51.7ms	remaining: 308ms
108:	learn: 0.6980392	test: 0.3671875	best: 0.4453125 (0)	total: 52.2ms	remaining: 307ms
109:	learn: 0.7000000	test: 0.3671875	best: 0.4453125 (0)	total: 52.7ms	remaining: 306ms
110:	learn: 0.7000000	test: 0.3593750	best: 0.4453125 (0)	total: 53.1ms	remaining: 306ms
111:	learn: 0.6960784	test: 0.3593750	best: 0.4453125 (0)	total: 53.6ms	remaining: 305ms
112:	learn: 0.7000000	test: 0.3671875	best: 0.4453125 (0)	total: 54ms	remaining: 305ms
113:	learn: 0.7000000	test: 0.3593750	best: 0.4453125 (0)	total: 54.5ms	remaining: 304ms
114:	learn: 0.7039216	test: 0.3671875	best: 0.4453125 (0)	total: 54.9ms	remaining: 303ms
115:	learn: 0.7058824	test: 0.3828125	best: 0.4453125 (0)	total: 55.5ms	remaining: 303ms
116:	learn: 0.7039216	test: 0.3750000	best: 0.4453125 (0)	total: 56ms	remaining: 303ms
117:	learn: 0.7058824	test: 0.3828125	best: 0.4453125 (0)	total: 56.4ms	remaining: 302ms
118:	learn: 0.7039216	test: 0.3828125	best: 0.4453125 (0)	total: 56.9ms	remaining: 301ms
119:	learn: 0.7039216	test: 0.3828125	best: 0.4453125 (0)	total: 57.3ms	remaining: 301ms
120:	learn: 0.7058824	test: 0.3671875	best: 0.4453125 (0)	total: 57.7ms	remaining: 300ms
121:	learn: 0.7039216	test: 0.3750000	best: 0.4453125 (0)	total: 58.2ms	remaining: 299ms
122:	learn: 0.7098039	test: 0.3750000	best: 0.4453125 (0)	total: 58.6ms	remaining: 299ms
123:	learn: 0.7117647	test: 0.3828125	best: 0.4453125 (0)	total: 59.1ms	remaining: 298ms
124:	learn: 0.7098039	test: 0.3828125	best: 0.4453125 (0)	total: 59.5ms	remaining: 298ms
125:	learn: 0.7098039	test: 0.3671875	best: 0.4453125 (0)	total: 60ms	remaining: 297ms
126:	learn: 0.7078431	test: 0.3750000	best: 0.4453125 (0)	total: 60.4ms	remaining: 296ms
127:	learn: 0.7078431	test: 0.3671875	best: 0.4453125 (0)	total: 60.9ms	remaining: 296ms
128:	learn: 0.7058824	test: 0.3671875	best: 0.4453125 (0)	total: 61.3ms	remaining: 295ms
129:	learn: 0.7098039	test: 0.3671875	best: 0.4453125 (0)	total: 61.8ms	remaining: 295ms
130:	learn: 0.7039216	test: 0.3671875	best: 0.4453125 (0)	total: 62.3ms	remaining: 294ms
131:	learn: 0.7098039	test: 0.3671875	best: 0.4453125 (0)	total: 62.7ms	remaining: 294ms
132:	learn: 0.7098039	test: 0.3671875	best: 0.4453125 (0)	total: 63.2ms	remaining: 293ms
133:	learn: 0.7117647	test: 0.3750000	best: 0.4453125 (0)	total: 63.6ms	remaining: 292ms
134:	learn: 0.7137255	test: 0.3828125	best: 0.4453125 (0)	total: 64.1ms	remaining: 292ms
135:	learn: 0.7137255	test: 0.3828125	best: 0.4453125 (0)	total: 64.5ms	remaining: 291ms
136:	learn: 0.7137255	test: 0.3828125	best: 0.4453125 (0)	total: 65ms	remaining: 291ms
137:	learn: 0.7156863	test: 0.3593750	best: 0.4453125 (0)	total: 65.4ms	remaining: 290ms
138:	learn: 0.7196078	test: 0.3593750	best: 0.4453125 (0)	total: 65.9ms	remaining: 290ms
139:	learn: 0.7254902	test: 0.3593750	best: 0.4453125 (0)	total: 66.4ms	remaining: 289ms
140:	learn: 0.7235294	test: 0.3593750	best: 0.4453125 (0)	total: 66.8ms	remaining: 289ms
141:	learn: 0.7215686	test: 0.3593750	best: 0.4453125 (0)	total: 67.3ms	remaining: 288ms
142:	learn: 0.7196078	test: 0.3515625	best: 0.4453125 (0)	total: 67.7ms	remaining: 287ms
143:	learn: 0.7215686	test: 0.3593750	best: 0.4453125 (0)	total: 68.2ms	remaining: 287ms
144:	learn: 0.7235294	test: 0.3671875	best: 0.4453125 (0)	total: 68.6ms	remaining: 286ms
145:	learn: 0.7235294	test: 0.3515625	best: 0.4453125 (0)	total: 69.1ms	remaining: 286ms
146:	learn: 0.7235294	test: 0.3515625	best: 0.4453125 (0)	total: 69.6ms	remaining: 286ms
147:	learn: 0.7254902	test: 0.3515625	best: 0.4453125 (0)	total: 70.1ms	remaining: 285ms
148:	learn: 0.7254902	test: 0.3515625	best: 0.4453125 (0)	total: 70.5ms	remaining: 284ms
149:	learn: 0.7235294	test: 0.3593750	best: 0.4453125 (0)	total: 71ms	remaining: 284ms
150:	learn: 0.7274510	test: 0.3515625	best: 0.4453125 (0)	total: 71.4ms	remaining: 283ms
151:	learn: 0.7235294	test: 0.3437500	best: 0.4453125 (0)	total: 72ms	remaining: 283ms
152:	learn: 0.7254902	test: 0.3515625	best: 0.4453125 (0)	total: 72.4ms	remaining: 283ms
153:	learn: 0.7254902	test: 0.3515625	best: 0.4453125 (0)	total: 72.9ms	remaining: 282ms
154:	learn: 0.7235294	test: 0.3515625	best: 0.4453125 (0)	total: 73.4ms	remaining: 282ms
155:	learn: 0.7294118	test: 0.3437500	best: 0.4453125 (0)	total: 73.9ms	remaining: 281ms
156:	learn: 0.7313725	test: 0.3359375	best: 0.4453125 (0)	total: 74.3ms	remaining: 281ms
157:	learn: 0.7313725	test: 0.3359375	best: 0.4453125 (0)	total: 74.8ms	remaining: 280ms
158:	learn: 0.7313725	test: 0.3437500	best: 0.4453125 (0)	total: 75.2ms	remaining: 280ms
159:	learn: 0.7313725	test: 0.3593750	best: 0.4453125 (0)	total: 75.7ms	remaining: 279ms
160:	learn: 0.7313725	test: 0.3593750	best: 0.4453125 (0)	total: 76.1ms	remaining: 279ms
161:	learn: 0.7313725	test: 0.3515625	best: 0.4453125 (0)	total: 76.6ms	remaining: 278ms
162:	learn: 0.7352941	test: 0.3437500	best: 0.4453125 (0)	total: 77.1ms	remaining: 278ms
163:	learn: 0.7352941	test: 0.3437500	best: 0.4453125 (0)	total: 77.5ms	remaining: 277ms
164:	learn: 0.7313725	test: 0.3515625	best: 0.4453125 (0)	total: 78ms	remaining: 276ms
165:	learn: 0.7333333	test: 0.3515625	best: 0.4453125 (0)	total: 78.4ms	remaining: 276ms
166:	learn: 0.7274510	test: 0.3671875	best: 0.4453125 (0)	total: 78.9ms	remaining: 275ms
167:	learn: 0.7274510	test: 0.3593750	best: 0.4453125 (0)	total: 79.3ms	remaining: 275ms
168:	learn: 0.7274510	test: 0.3515625	best: 0.4453125 (0)	total: 79.8ms	remaining: 274ms
169:	learn: 0.7254902	test: 0.3593750	best: 0.4453125 (0)	total: 80.2ms	remaining: 274ms
170:	learn: 0.7294118	test: 0.3437500	best: 0.4453125 (0)	total: 80.7ms	remaining: 273ms
171:	learn: 0.7313725	test: 0.3437500	best: 0.4453125 (0)	total: 81.1ms	remaining: 273ms
172:	learn: 0.7294118	test: 0.3437500	best: 0.4453125 (0)	total: 81.6ms	remaining: 272ms
173:	learn: 0.7294118	test: 0.3437500	best: 0.4453125 (0)	total: 82ms	remaining: 272ms
174:	learn: 0.7372549	test: 0.3359375	best: 0.4453125 (0)	total: 82.5ms	remaining: 271ms
175:	learn: 0.7352941	test: 0.3437500	best: 0.4453125 (0)	total: 82.9ms	remaining: 270ms
176:	learn: 0.7333333	test: 0.3437500	best: 0.4453125 (0)	total: 83.4ms	remaining: 270ms
177:	learn: 0.7372549	test: 0.3437500	best: 0.4453125 (0)	total: 83.9ms	remaining: 270ms
178:	learn: 0.7372549	test: 0.3515625	best: 0.4453125 (0)	total: 84.3ms	remaining: 269ms
179:	learn: 0.7352941	test: 0.3515625	best: 0.4453125 (0)	total: 84.8ms	remaining: 268ms
180:	learn: 0.7313725	test: 0.3359375	best: 0.4453125 (0)	total: 85.4ms	remaining: 268ms
181:	learn: 0.7294118	test: 0.3437500	best: 0.4453125 (0)	total: 85.8ms	remaining: 268ms
182:	learn: 0.7235294	test: 0.3437500	best: 0.4453125 (0)	total: 86.3ms	remaining: 267ms
183:	learn: 0.7274510	test: 0.3359375	best: 0.4453125 (0)	total: 86.7ms	remaining: 267ms
184:	learn: 0.7352941	test: 0.3281250	best: 0.4453125 (0)	total: 87.3ms	remaining: 267ms
185:	learn: 0.7333333	test: 0.3281250	best: 0.4453125 (0)	total: 87.7ms	remaining: 266ms
186:	learn: 0.7294118	test: 0.3281250	best: 0.4453125 (0)	total: 88.2ms	remaining: 266ms
187:	learn: 0.7313725	test: 0.3281250	best: 0.4453125 (0)	total: 88.7ms	remaining: 265ms
188:	learn: 0.7333333	test: 0.3281250	best: 0.4453125 (0)	total: 89.3ms	remaining: 265ms
189:	learn: 0.7392157	test: 0.3281250	best: 0.4453125 (0)	total: 89.8ms	remaining: 265ms
190:	learn: 0.7392157	test: 0.3281250	best: 0.4453125 (0)	total: 90.3ms	remaining: 264ms
191:	learn: 0.7372549	test: 0.3281250	best: 0.4453125 (0)	total: 90.8ms	remaining: 264ms
192:	learn: 0.7411765	test: 0.3281250	best: 0.4453125 (0)	total: 91.3ms	remaining: 264ms
193:	learn: 0.7431373	test: 0.3281250	best: 0.4453125 (0)	total: 91.8ms	remaining: 263ms
194:	learn: 0.7470588	test: 0.3281250	best: 0.4453125 (0)	total: 92.4ms	remaining: 263ms
195:	learn: 0.7470588	test: 0.3281250	best: 0.4453125 (0)	total: 93ms	remaining: 263ms
196:	learn: 0.7470588	test: 0.3281250	best: 0.4453125 (0)	total: 93.5ms	remaining: 262ms
197:	learn: 0.7490196	test: 0.3281250	best: 0.4453125 (0)	total: 93.9ms	remaining: 262ms
198:	learn: 0.7470588	test: 0.3359375	best: 0.4453125 (0)	total: 94.4ms	remaining: 261ms
199:	learn: 0.7450980	test: 0.3359375	best: 0.4453125 (0)	total: 94.9ms	remaining: 261ms
200:	learn: 0.7470588	test: 0.3359375	best: 0.4453125 (0)	total: 95.4ms	remaining: 261ms
201:	learn: 0.7490196	test: 0.3281250	best: 0.4453125 (0)	total: 96.7ms	remaining: 262ms
202:	learn: 0.7490196	test: 0.3359375	best: 0.4453125 (0)	total: 97.2ms	remaining: 262ms
203:	learn: 0.7529412	test: 0.3281250	best: 0.4453125 (0)	total: 97.7ms	remaining: 262ms
204:	learn: 0.7509804	test: 0.3281250	best: 0.4453125 (0)	total: 98.2ms	remaining: 261ms
205:	learn: 0.7529412	test: 0.3359375	best: 0.4453125 (0)	total: 98.7ms	remaining: 261ms
206:	learn: 0.7529412	test: 0.3281250	best: 0.4453125 (0)	total: 99.1ms	remaining: 260ms
207:	learn: 0.7549020	test: 0.3203125	best: 0.4453125 (0)	total: 99.6ms	remaining: 260ms
208:	learn: 0.7549020	test: 0.3359375	best: 0.4453125 (0)	total: 100ms	remaining: 259ms
209:	learn: 0.7549020	test: 0.3359375	best: 0.4453125 (0)	total: 101ms	remaining: 259ms
210:	learn: 0.7568627	test: 0.3515625	best: 0.4453125 (0)	total: 101ms	remaining: 259ms
211:	learn: 0.7568627	test: 0.3437500	best: 0.4453125 (0)	total: 102ms	remaining: 258ms
212:	learn: 0.7509804	test: 0.3437500	best: 0.4453125 (0)	total: 102ms	remaining: 258ms
213:	learn: 0.7490196	test: 0.3437500	best: 0.4453125 (0)	total: 103ms	remaining: 257ms
214:	learn: 0.7549020	test: 0.3515625	best: 0.4453125 (0)	total: 103ms	remaining: 257ms
215:	learn: 0.7568627	test: 0.3281250	best: 0.4453125 (0)	total: 104ms	remaining: 256ms
216:	learn: 0.7549020	test: 0.3359375	best: 0.4453125 (0)	total: 104ms	remaining: 256ms
217:	learn: 0.7529412	test: 0.3359375	best: 0.4453125 (0)	total: 105ms	remaining: 255ms
218:	learn: 0.7529412	test: 0.3437500	best: 0.4453125 (0)	total: 105ms	remaining: 255ms
219:	learn: 0.7509804	test: 0.3437500	best: 0.4453125 (0)	total: 106ms	remaining: 254ms
220:	learn: 0.7549020	test: 0.3515625	best: 0.4453125 (0)	total: 106ms	remaining: 254ms
221:	learn: 0.7529412	test: 0.3437500	best: 0.4453125 (0)	total: 107ms	remaining: 253ms
222:	learn: 0.7529412	test: 0.3515625	best: 0.4453125 (0)	total: 107ms	remaining: 253ms
223:	learn: 0.7549020	test: 0.3515625	best: 0.4453125 (0)	total: 107ms	remaining: 252ms
224:	learn: 0.7549020	test: 0.3437500	best: 0.4453125 (0)	total: 108ms	remaining: 252ms
225:	learn: 0.7568627	test: 0.3437500	best: 0.4453125 (0)	total: 108ms	remaining: 251ms

In [14]:
cb3 = CatBoostClassifier(
    iterations=200,
    learning_rate=0.1,
    depth=3,
    l2_leaf_reg=3,
    bagging_temperature=0.5,
    random_strength=1,
    eval_metric='Accuracy',
    early_stopping_rounds=20,
    verbose=50,
    random_state=42
)

cb3.fit(
    preprocessed_X_train, y_train,
    eval_set=(preprocessed_X_valid, y_valid),
    # plot=True
)

fit_and_add_and_KFoldmean3_for_boost(cb3, 'CatBoostClassifier3')

0:	learn: 0.4176471	test: 0.3593750	best: 0.3593750 (0)	total: 784us	remaining: 156ms
Stopped by overfitting detector  (20 iterations wait)

bestTest = 0.40625
bestIteration = 19

Shrink model to first 20 iterations.
0:	learn: 0.4494118	total: 501us	remaining: 99.7ms
50:	learn: 0.5552941	total: 21.7ms	remaining: 63.5ms
100:	learn: 0.6470588	total: 42.5ms	remaining: 41.7ms
150:	learn: 0.6941176	total: 63ms	remaining: 20.5ms
199:	learn: 0.7458824	total: 84.1ms	remaining: 0us
0:	learn: 0.4235294	total: 484us	remaining: 96.4ms
50:	learn: 0.5458824	total: 21.4ms	remaining: 62.5ms
100:	learn: 0.6305882	total: 45ms	remaining: 44.1ms
150:	learn: 0.6800000	total: 70.4ms	remaining: 22.8ms
199:	learn: 0.7176471	total: 98.9ms	remaining: 0us
0:	learn: 0.4131455	total: 727us	remaining: 145ms
50:	learn: 0.5539906	total: 22.6ms	remaining: 66.1ms
100:	learn: 0.6502347	total: 44.6ms	remaining: 43.7ms
150:	learn: 0.6924883	total: 66.4ms	remaining: 21.6ms
199:	learn: 0.7464789	total: 89.6ms	remaining: 0us

In [15]:
# import optuna
# from optuna.samplers import TPESampler
# from catboost import CatBoostClassifier
# from sklearn.model_selection import GroupKFold, GroupShuffleSplit
# from sklearn.metrics import accuracy_score
# from sklearn.preprocessing import LabelEncoder
# import pandas as pd
# import numpy as np

# # ----------------------------
# # 1. Подготовка данных (предполагается, что df_model уже создан)
# # ----------------------------
# exclude_cols = ['match_id', 'player_name', 'next_opp_move']
# X = df_model.drop(columns=exclude_cols, errors='ignore')
# y = LabelEncoder().fit_transform(df_model['next_opp_move'])
# groups = df_model['match_id'].values

# # Список категориальных признаков
# cat_features = [
#     'win_category', 'stake', 'opp_move', 'my_move', 'outcome',
#     'prev_opp_move', 'prev_outcome', 'prev2_opp_move', 'prev2_outcome'
# ]
# cat_features = [col for col in cat_features if col in X.columns]

# # Приводим категориальные колонки к типу 'category'
# for col in cat_features:
#     X[col] = X[col].astype('category')

# # Остальные колонки делаем числовыми
# for col in X.columns:
#     if col not in cat_features:
#         X[col] = pd.to_numeric(X[col], errors='coerce').fillna(0)

# # ----------------------------
# # 2. Функция цели для Optuna
# # ----------------------------
# def objective(trial):
#     params = {
#         'iterations': trial.suggest_int('iterations', 300, 1200, step=50),
#         'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
#         'depth': trial.suggest_int('depth', 3, 10),
#         'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 0.1, 10.0, log=True),
#         'border_count': trial.suggest_int('border_count', 32, 255),
#         'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.6, 1.0),
#         'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 50),
#         'random_seed': 42,
#         'verbose': 0,
#         'cat_features': cat_features
#     }
    
#     model = CatBoostClassifier(**params)
#     gkf = GroupKFold(n_splits=5)
#     acc_scores = []
    
#     for train_idx, val_idx in gkf.split(X, y, groups):
#         X_train_fold = X.iloc[train_idx]
#         X_val_fold = X.iloc[val_idx]
#         y_train_fold = y[train_idx]
#         y_val_fold = y[val_idx]
        
#         model.fit(
#             X_train_fold, y_train_fold,
#             eval_set=(X_val_fold, y_val_fold),
#             early_stopping_rounds=50,
#             verbose=False
#         )
#         y_pred = model.predict(X_val_fold)
#         acc = accuracy_score(y_val_fold, y_pred)
#         acc_scores.append(acc)
    
#     return np.mean(acc_scores)

# # ----------------------------
# # 3. Запуск оптимизации
# # ----------------------------
# study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))
# study.optimize(objective, n_trials=200, show_progress_bar=True)

# print("Лучшие гиперпараметры:", study.best_params)
# print("Лучшая точность кросс-валидации:", study.best_value)

# # ----------------------------
# # 4. Финальное обучение на валидационном разбиении
# # ----------------------------
# gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
# train_idx, valid_idx = next(gss.split(X, y, groups))
# X_train, X_valid = X.iloc[train_idx], X.iloc[valid_idx]
# y_train, y_valid = y[train_idx], y[valid_idx]

# best_params = study.best_params.copy()
# best_params['random_seed'] = 42
# best_params['verbose'] = 100
# best_params['cat_features'] = cat_features

# final_model = CatBoostClassifier(**best_params)
# final_model.fit(
#     X_train, y_train,
#     eval_set=(X_valid, y_valid),
#     early_stopping_rounds=50,
#     verbose=100
# )

# y_pred_valid = final_model.predict(X_valid)
# valid_acc = accuracy_score(y_valid, y_pred_valid)
# print(f"Точность на валидации: {valid_acc:.4f}")

In [16]:
lgbm = lgb.LGBMClassifier(
    objective='multiclass',       # многоклассовая классификация
    num_class=3,                  # количество классов
    boosting_type='gbdt',
    max_depth=3,
    num_leaves=3,
    subsample_freq=7,
    learning_rate=0.030893841756247098,
    n_estimators=650,
    random_state=42,
    subsample=0.8480028285364561,
    colsample_bytree=0.7726648252169472,
    reg_alpha=1.3973254101399392e-06,
    reg_lambda=0.0004107390806915259,
    min_child_samples=9,
    verbose=-1
)


lgbm.fit(
    preprocessed_X_train,
    y_train,
    eval_set=[(preprocessed_X_valid, y_valid)],
    eval_metric='multi_logloss',
    callbacks=[lgb.early_stopping(stopping_rounds=50),   # ранняя остановка
               lgb.log_evaluation(period=10)]            # логирование каждые 10 итераций
)

fit_and_add_and_KFoldmean3_for_boost(lgbm, 'LGBMClassifier')

Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.09185
[20]	valid_0's multi_logloss: 1.09366
[30]	valid_0's multi_logloss: 1.09748
[40]	valid_0's multi_logloss: 1.09314
[50]	valid_0's multi_logloss: 1.09848
Early stopping, best iteration is:
[1]	valid_0's multi_logloss: 1.0885

In [17]:
xgboost = xgb.XGBClassifier(
    objective='multi:softprob',        # многоклассовая классификация (вероятности)
    num_class=3,                       # количество классов
    eval_metric='mlogloss',            # метрика для многоклассовой задачи (или 'merror')
    max_depth=3,
    learning_rate=0.028501619102234265,
    n_estimators=600,
    subsample=0.8877943054742949,
    colsample_bytree=0.6960566694104567,
    colsample_bylevel=0.9460737167069979,
    reg_alpha=0.0002900813074581903,
    reg_lambda=0.001995414273777448,
    gamma=3.296006537275762e-05,
    min_child_weight=4.993110176167802,
    max_delta_step=8.696994123368121,
    random_state=42,
    use_label_encoder=False,
    verbosity=0,
    n_jobs=-1
)

xgboost.fit(
    preprocessed_X_train,
    y_train,
    eval_set=[(preprocessed_X_valid, y_valid)],
    verbose=True
)

fit_and_add_and_KFoldmean3_for_boost(xgboost, 'XGBClassifier')

[0]	validation_0-mlogloss:1.08805
[1]	validation_0-mlogloss:1.08810
[2]	validation_0-mlogloss:1.08826
[3]	validation_0-mlogloss:1.08887
[4]	validation_0-mlogloss:1.08956
[5]	validation_0-mlogloss:1.08938
[6]	validation_0-mlogloss:1.08992
[7]	validation_0-mlogloss:1.09009
[8]	validation_0-mlogloss:1.09127
[9]	validation_0-mlogloss:1.09081
[10]	validation_0-mlogloss:1.09163
[11]	validation_0-mlogloss:1.09211
[12]	validation_0-mlogloss:1.09266
[13]	validation_0-mlogloss:1.09379
[14]	validation_0-mlogloss:1.09382
[15]	validation_0-mlogloss:1.09417
[16]	validation_0-mlogloss:1.09449
[17]	validation_0-mlogloss:1.09553
[18]	validation_0-mlogloss:1.09587
[19]	validation_0-mlogloss:1.09646
[20]	validation_0-mlogloss:1.09711
[21]	validation_0-mlogloss:1.09805
[22]	validation_0-mlogloss:1.09813
[23]	validation_0-mlogloss:1.09881
[24]	validation_0-mlogloss:1.09906
[25]	validation_0-mlogloss:1.09960
[26]	validation_0-mlogloss:1.10037
[27]	validation_0-mlogloss:1.10067
[28]	validation_0-mlogloss:1.10049
[29]	validation_0-mlogloss:1.10046
[30]	validation_0-mlogloss:1.10101
[31]	validation_0-mlogloss:1.10168
[32]	validation_0-mlogloss:1.10167
[33]	validation_0-mlogloss:1.10194
[34]	validation_0-mlogloss:1.10186
[35]	validation_0-mlogloss:1.10198
[36]	validation_0-mlogloss:1.10281
[37]	validation_0-mlogloss:1.10273
[38]	validation_0-mlogloss:1.10320
[39]	validation_0-mlogloss:1.10354
[40]	validation_0-mlogloss:1.10360
[41]	validation_0-mlogloss:1.10448
[42]	validation_0-mlogloss:1.10488
[43]	validation_0-mlogloss:1.10561
[44]	validation_0-mlogloss:1.10567
[45]	validation_0-mlogloss:1.10649
[46]	validation_0-mlogloss:1.10638
[47]	validation_0-mlogloss:1.10657
[48]	validation_0-mlogloss:1.10657
[49]	validation_0-mlogloss:1.10737
[50]	validation_0-mlogloss:1.10809
[51]	validation_0-mlogloss:1.10932
[52]	validation_0-mlogloss:1.10952
[53]	validation_0-mlogloss:1.10980
[54]	validation_0-mlogloss:1.10952
[55]	validation_0-mlogloss:1.10962
[56]	validation_0-mlogloss:1.11004
[57]	validation_0-mlogloss:1.10968
[58]	validation_0-mlogloss:1.11060
[59]	validation_0-mlogloss:1.11168
[60]	validation_0-mlogloss:1.11220
[61]	validation_0-mlogloss:1.11277
[62]	validation_0-mlogloss:1.11264
[63]	validation_0-mlogloss:1.11302
[64]	validation_0-mlogloss:1.11277
[65]	validation_0-mlogloss:1.11340
[66]	validation_0-mlogloss:1.11412
[67]	validation_0-mlogloss:1.11440
[68]	validation_0-mlogloss:1.11482
[69]	validation_0-mlogloss:1.11556
[70]	validation_0-mlogloss:1.11542
[71]	validation_0-mlogloss:1.11603
[72]	validation_0-mlogloss:1.11663
[73]	validation_0-mlogloss:1.11718
[74]	validation_0-mlogloss:1.11695
[75]	validation_0-mlogloss:1.11726
[76]	validation_0-mlogloss:1.11773
[77]	validation_0-mlogloss:1.11827
[78]	validation_0-mlogloss:1.11875
[79]	validation_0-mlogloss:1.11912
[80]	validation_0-mlogloss:1.12037
[81]	validation_0-mlogloss:1.12068
[82]	validation_0-mlogloss:1.12128
[83]	validation_0-mlogloss:1.12108
[84]	validation_0-mlogloss:1.12134
[85]	validation_0-mlogloss:1.12194
[86]	validation_0-mlogloss:1.12209
[87]	validation_0-mlogloss:1.12250
[88]	validation_0-mlogloss:1.12233
[89]	validation_0-mlogloss:1.12304
[90]	validation_0-mlogloss:1.12375
[91]	validation_0-mlogloss:1.12387
[92]	validation_0-mlogloss:1.12406
[93]	validation_0-mlogloss:1.12431
[94]	validation_0-mlogloss:1.12424
[95]	validation_0-mlogloss:1.12471
[96]	validation_0-mlogloss:1.12507
[97]	validation_0-mlogloss:1.12478
[98]	validation_0-mlogloss:1.12516
[99]	validation_0-mlogloss:1.12581
[100]	validation_0-mlogloss:1.12645
[101]	validation_0-mlogloss:1.12657
[102]	validation_0-mlogloss:1.12632
[103]	validation_0-mlogloss:1.12652
[104]	validation_0-mlogloss:1.12672
[105]	validation_0-mlogloss:1.12648
[106]	validation_0-mlogloss:1.12804
[107]	validation_0-mlogloss:1.12912
[108]	validation_0-mlogloss:1.12975
[109]	validation_0-mlogloss:1.13026
[110]	validation_0-mlogloss:1.13018
[111]	validation_0-mlogloss:1.13046
[112]	validation_0-mlogloss:1.13073
[113]	validation_0-mlogloss:1.13072
[114]	validation_0-mlogloss:1.13168
[115]	validation_0-mlogloss:1.13255
[116]	validation_0-mlogloss:1.13241
[117]	validation_0-mlogloss:1.13243
[118]	validation_0-mlogloss:1.13291
[119]	validation_0-mlogloss:1.13263
[120]	validation_0-mlogloss:1.13328
[121]	validation_0-mlogloss:1.13438
[122]	validation_0-mlogloss:1.13485
[123]	validation_0-mlogloss:1.13483
[124]	validation_0-mlogloss:1.13494
[125]	validation_0-mlogloss:1.13482
[126]	validation_0-mlogloss:1.13487
[127]	validation_0-mlogloss:1.13494
[128]	validation_0-mlogloss:1.13566
[129]	validation_0-mlogloss:1.13553
[130]	validation_0-mlogloss:1.13577
[131]	validation_0-mlogloss:1.13550
[132]	validation_0-mlogloss:1.13626
[133]	validation_0-mlogloss:1.13667
[134]	validation_0-mlogloss:1.13705
[135]	validation_0-mlogloss:1.13767
[136]	validation_0-mlogloss:1.13819
[137]	validation_0-mlogloss:1.13889
[138]	validation_0-mlogloss:1.13915
[139]	validation_0-mlogloss:1.13966
[140]	validation_0-mlogloss:1.14022
[141]	validation_0-mlogloss:1.14093
[142]	validation_0-mlogloss:1.14100
[143]	validation_0-mlogloss:1.14166
[144]	validation_0-mlogloss:1.14190
[145]	validation_0-mlogloss:1.14146
[146]	validation_0-mlogloss:1.14163
[147]	validation_0-mlogloss:1.14234
[148]	validation_0-mlogloss:1.14239
[149]	validation_0-mlogloss:1.14238
[150]	validation_0-mlogloss:1.14264
[151]	validation_0-mlogloss:1.14313
[152]	validation_0-mlogloss:1.14315
[153]	validation_0-mlogloss:1.14371
[154]	validation_0-mlogloss:1.14392
[155]	validation_0-mlogloss:1.14341
[156]	validation_0-mlogloss:1.14359
[157]	validation_0-mlogloss:1.14403
[158]	validation_0-mlogloss:1.14502
[159]	validation_0-mlogloss:1.14551
[160]	validation_0-mlogloss:1.14558
[161]	validation_0-mlogloss:1.14608
[162]	validation_0-mlogloss:1.14651
[163]	validation_0-mlogloss:1.14680
[164]	validation_0-mlogloss:1.14695
[165]	validation_0-mlogloss:1.14723
[166]	validation_0-mlogloss:1.14795
[167]	validation_0-mlogloss:1.14826
[168]	validation_0-mlogloss:1.14815
[169]	validation_0-mlogloss:1.14854
[170]	validation_0-mlogloss:1.14819
[171]	validation_0-mlogloss:1.14817
[172]	validation_0-mlogloss:1.14830
[173]	validation_0-mlogloss:1.14855
[174]	validation_0-mlogloss:1.14920
[175]	validation_0-mlogloss:1.14941
[176]	validation_0-mlogloss:1.15004
[177]	validation_0-mlogloss:1.15008
[178]	validation_0-mlogloss:1.14997
[179]	validation_0-mlogloss:1.15019
[180]	validation_0-mlogloss:1.14936
[181]	validation_0-mlogloss:1.14952
[182]	validation_0-mlogloss:1.15015
[183]	validation_0-mlogloss:1.15008
[184]	validation_0-mlogloss:1.15041
[185]	validation_0-mlogloss:1.15052
[186]	validation_0-mlogloss:1.15092
[187]	validation_0-mlogloss:1.15095
[188]	validation_0-mlogloss:1.15106
[189]	validation_0-mlogloss:1.15168
[190]	validation_0-mlogloss:1.15159
[191]	validation_0-mlogloss:1.15246
[192]	validation_0-mlogloss:1.15304
[193]	validation_0-mlogloss:1.15386
[194]	validation_0-mlogloss:1.15403
[195]	validation_0-mlogloss:1.15400
[196]	validation_0-mlogloss:1.15345
[197]	validation_0-mlogloss:1.15408
[198]	validation_0-mlogloss:1.15429
[199]	validation_0-mlogloss:1.15419
[200]	validation_0-mlogloss:1.15376
[201]	validation_0-mlogloss:1.15396
[202]	validation_0-mlogloss:1.15508
[203]	validation_0-mlogloss:1.15530
[204]	validation_0-mlogloss:1.15614
[205]	validation_0-mlogloss:1.15663
[206]	validation_0-mlogloss:1.15679
[207]	validation_0-mlogloss:1.15879
[208]	validation_0-mlogloss:1.15910
[209]	validation_0-mlogloss:1.15916
[210]	validation_0-mlogloss:1.15922
[211]	validation_0-mlogloss:1.15959
[212]	validation_0-mlogloss:1.15990
[213]	validation_0-mlogloss:1.16094
[214]	validation_0-mlogloss:1.16093
[215]	validation_0-mlogloss:1.16179
[216]	validation_0-mlogloss:1.16153
[217]	validation_0-mlogloss:1.16207
[218]	validation_0-mlogloss:1.16248
[219]	validation_0-mlogloss:1.16281
[220]	validation_0-mlogloss:1.16349
[221]	validation_0-mlogloss:1.16397
[222]	validation_0-mlogloss:1.16396
[223]	validation_0-mlogloss:1.16419
[224]	validation_0-mlogloss:1.16431
[225]	validation_0-mlogloss:1.16461
[226]	validation_0-mlogloss:1.16507
[227]	validation_0-mlogloss:1.16573
[228]	validation_0-mlogloss:1.16621
[229]	validation_0-mlogloss:1.16604
[230]	validation_0-mlogloss:1.16688
[231]	validation_0-mlogloss:1.16724
[232]	validation_0-mlogloss:1.16706
[233]	validation_0-mlogloss:1.16720
[234]	validation_0-mlogloss:1.16753
[235]	validation_0-mlogloss:1.16801
[236]	validation_0-mlogloss:1.16805
[237]	validation_0-mlogloss:1.16916
[238]	validation_0-mlogloss:1.16966
[239]	validation_0-mlogloss:1.16996
[240]	validation_0-mlogloss:1.17047
[241]	validation_0-mlogloss:1.17117
[242]	validation_0-mlogloss:1.17145
[243]	validation_0-mlogloss:1.17157
[244]	validation_0-mlogloss:1.17182
[245]	validation_0-mlogloss:1.17168
[246]	validation_0-mlogloss:1.17229
[247]	validation_0-mlogloss:1.17246
[248]	validation_0-mlogloss:1.17292
[249]	validation_0-mlogloss:1.17435
[250]	validation_0-mlogloss:1.17409
[251]	validation_0-mlogloss:1.17406
[252]	validation_0-mlogloss:1.17496
[253]	validation_0-mlogloss:1.17525
[254]	validation_0-mlogloss:1.17525
[255]	validation_0-mlogloss:1.17533
[256]	validation_0-mlogloss:1.17501
[257]	validation_0-mlogloss:1.17542
[258]	validation_0-mlogloss:1.17537
[259]	validation_0-mlogloss:1.17594
[260]	validation_0-mlogloss:1.17582
[261]	validation_0-mlogloss:1.17640
[262]	validation_0-mlogloss:1.17606
[263]	validation_0-mlogloss:1.17624
[264]	validation_0-mlogloss:1.17589
[265]	validation_0-mlogloss:1.17667
[266]	validation_0-mlogloss:1.17737
[267]	validation_0-mlogloss:1.17722
[268]	validation_0-mlogloss:1.17738
[269]	validation_0-mlogloss:1.17708
[270]	validation_0-mlogloss:1.17709
[271]	validation_0-mlogloss:1.17759
[272]	validation_0-mlogloss:1.17779
[273]	validation_0-mlogloss:1.17741
[274]	validation_0-mlogloss:1.17864
[275]	validation_0-mlogloss:1.17874
[276]	validation_0-mlogloss:1.17864
[277]	validation_0-mlogloss:1.17880
[278]	validation_0-mlogloss:1.17841
[279]	validation_0-mlogloss:1.17898
[280]	validation_0-mlogloss:1.17930
[281]	validation_0-mlogloss:1.17957
[282]	validation_0-mlogloss:1.17995
[283]	validation_0-mlogloss:1.18044
[284]	validation_0-mlogloss:1.18057
[285]	validation_0-mlogloss:1.18123
[286]	validation_0-mlogloss:1.18229
[287]	validation_0-mlogloss:1.18287
[288]	validation_0-mlogloss:1.18308
[289]	validation_0-mlogloss:1.18322
[290]	validation_0-mlogloss:1.18403
[291]	validation_0-mlogloss:1.18456
[292]	validation_0-mlogloss:1.18524
[293]	validation_0-mlogloss:1.18571
[294]	validation_0-mlogloss:1.18630
[295]	validation_0-mlogloss:1.18725
[296]	validation_0-mlogloss:1.18781
[297]	validation_0-mlogloss:1.18798
[298]	validation_0-mlogloss:1.18823
[299]	validation_0-mlogloss:1.18806
[300]	validation_0-mlogloss:1.18802
[301]	validation_0-mlogloss:1.18812
[302]	validation_0-mlogloss:1.18771
[303]	validation_0-mlogloss:1.18778
[304]	validation_0-mlogloss:1.18756
[305]	validation_0-mlogloss:1.18774
[306]	validation_0-mlogloss:1.18872
[307]	validation_0-mlogloss:1.18898
[308]	validation_0-mlogloss:1.18889
[309]	validation_0-mlogloss:1.18919
[310]	validation_0-mlogloss:1.18905
[311]	validation_0-mlogloss:1.18867
[312]	validation_0-mlogloss:1.18869
[313]	validation_0-mlogloss:1.18901
[314]	validation_0-mlogloss:1.18905
[315]	validation_0-mlogloss:1.18851
[316]	validation_0-mlogloss:1.18854
[317]	validation_0-mlogloss:1.18865
[318]	validation_0-mlogloss:1.18934
[319]	validation_0-mlogloss:1.18981
[320]	validation_0-mlogloss:1.19065
[321]	validation_0-mlogloss:1.19107
[322]	validation_0-mlogloss:1.19170
[323]	validation_0-mlogloss:1.19141
[324]	validation_0-mlogloss:1.19158
[325]	validation_0-mlogloss:1.19102
[326]	validation_0-mlogloss:1.19107
[327]	validation_0-mlogloss:1.19099
[328]	validation_0-mlogloss:1.19112
[329]	validation_0-mlogloss:1.19131
[330]	validation_0-mlogloss:1.19150
[331]	validation_0-mlogloss:1.19186
[332]	validation_0-mlogloss:1.19244
[333]	validation_0-mlogloss:1.19275
[334]	validation_0-mlogloss:1.19284
[335]	validation_0-mlogloss:1.19338
[336]	validation_0-mlogloss:1.19397
[337]	validation_0-mlogloss:1.19436
[338]	validation_0-mlogloss:1.19444
[339]	validation_0-mlogloss:1.19448
[340]	validation_0-mlogloss:1.19427
[341]	validation_0-mlogloss:1.19432
[342]	validation_0-mlogloss:1.19452
[343]	validation_0-mlogloss:1.19493
[344]	validation_0-mlogloss:1.19594
[345]	validation_0-mlogloss:1.19574
[346]	validation_0-mlogloss:1.19635
[347]	validation_0-mlogloss:1.19610
[348]	validation_0-mlogloss:1.19638
[349]	validation_0-mlogloss:1.19692
[350]	validation_0-mlogloss:1.19720
[351]	validation_0-mlogloss:1.19804
[352]	validation_0-mlogloss:1.19793
[353]	validation_0-mlogloss:1.19799
[354]	validation_0-mlogloss:1.19802
[355]	validation_0-mlogloss:1.19856
[356]	validation_0-mlogloss:1.19884
[357]	validation_0-mlogloss:1.19891
[358]	validation_0-mlogloss:1.19928
[359]	validation_0-mlogloss:1.19962
[360]	validation_0-mlogloss:1.19917
[361]	validation_0-mlogloss:1.20004
[362]	validation_0-mlogloss:1.20040
[363]	validation_0-mlogloss:1.20076
[364]	validation_0-mlogloss:1.20079
[365]	validation_0-mlogloss:1.20116
[366]	validation_0-mlogloss:1.20160
[367]	validation_0-mlogloss:1.20176
[368]	validation_0-mlogloss:1.20218
[369]	validation_0-mlogloss:1.20301
[370]	validation_0-mlogloss:1.20243
[371]	validation_0-mlogloss:1.20241
[372]	validation_0-mlogloss:1.20291
[373]	validation_0-mlogloss:1.20254
[374]	validation_0-mlogloss:1.20226
[375]	validation_0-mlogloss:1.20203
[376]	validation_0-mlogloss:1.20266
[377]	validation_0-mlogloss:1.20250
[378]	validation_0-mlogloss:1.20211
[379]	validation_0-mlogloss:1.20282
[380]	validation_0-mlogloss:1.20353
[381]	validation_0-mlogloss:1.20416
[382]	validation_0-mlogloss:1.20369
[383]	validation_0-mlogloss:1.20463
[384]	validation_0-mlogloss:1.20539
[385]	validation_0-mlogloss:1.20554
[386]	validation_0-mlogloss:1.20567
[387]	validation_0-mlogloss:1.20591
[388]	validation_0-mlogloss:1.20718
[389]	validation_0-mlogloss:1.20761
[390]	validation_0-mlogloss:1.20789
[391]	validation_0-mlogloss:1.20814
[392]	validation_0-mlogloss:1.20839
[393]	validation_0-mlogloss:1.20871
[394]	validation_0-mlogloss:1.20896
[395]	validation_0-mlogloss:1.20864
[396]	validation_0-mlogloss:1.20878
[397]	validation_0-mlogloss:1.20945
[398]	validation_0-mlogloss:1.20987
[399]	validation_0-mlogloss:1.20979
[400]	validation_0-mlogloss:1.20969
[401]	validation_0-mlogloss:1.21073
[402]	validation_0-mlogloss:1.21097
[403]	validation_0-mlogloss:1.21156
[404]	validation_0-mlogloss:1.21183
[405]	validation_0-mlogloss:1.21247
[406]	validation_0-mlogloss:1.21270
[407]	validation_0-mlogloss:1.21249
[408]	validation_0-mlogloss:1.21303
[409]	validation_0-mlogloss:1.21342
[410]	validation_0-mlogloss:1.21361
[411]	validation_0-mlogloss:1.21339
[412]	validation_0-mlogloss:1.21332
[413]	validation_0-mlogloss:1.21459
[414]	validation_0-mlogloss:1.21486
[415]	validation_0-mlogloss:1.21544
[416]	validation_0-mlogloss:1.21581
[417]	validation_0-mlogloss:1.21587
[418]	validation_0-mlogloss:1.21643
[419]	validation_0-mlogloss:1.21563
[420]	validation_0-mlogloss:1.21612
[421]	validation_0-mlogloss:1.21620
[422]	validation_0-mlogloss:1.21702
[423]	validation_0-mlogloss:1.21702
[424]	validation_0-mlogloss:1.21720
[425]	validation_0-mlogloss:1.21728
[426]	validation_0-mlogloss:1.21720
[427]	validation_0-mlogloss:1.21682
[428]	validation_0-mlogloss:1.21731
[429]	validation_0-mlogloss:1.21766
[430]	validation_0-mlogloss:1.21835
[431]	validation_0-mlogloss:1.21907
[432]	validation_0-mlogloss:1.21935
[433]	validation_0-mlogloss:1.21912
[434]	validation_0-mlogloss:1.21908
[435]	validation_0-mlogloss:1.21900
[436]	validation_0-mlogloss:1.21879
[437]	validation_0-mlogloss:1.21900
[438]	validation_0-mlogloss:1.21879
[439]	validation_0-mlogloss:1.21882
[440]	validation_0-mlogloss:1.21915
[441]	validation_0-mlogloss:1.21886
[442]	validation_0-mlogloss:1.21911
[443]	validation_0-mlogloss:1.21895
[444]	validation_0-mlogloss:1.21926
[445]	validation_0-mlogloss:1.21970
[446]	validation_0-mlogloss:1.22017
[447]	validation_0-mlogloss:1.22053
[448]	validation_0-mlogloss:1.22098
[449]	validation_0-mlogloss:1.22038
[450]	validation_0-mlogloss:1.22023
[451]	validation_0-mlogloss:1.22015
[452]	validation_0-mlogloss:1.22048
[453]	validation_0-mlogloss:1.22086
[454]	validation_0-mlogloss:1.22160
[455]	validation_0-mlogloss:1.22188
[456]	validation_0-mlogloss:1.22166
[457]	validation_0-mlogloss:1.22209
[458]	validation_0-mlogloss:1.22262
[459]	validation_0-mlogloss:1.22296
[460]	validation_0-mlogloss:1.22343
[461]	validation_0-mlogloss:1.22302
[462]	validation_0-mlogloss:1.22328
[463]	validation_0-mlogloss:1.22305
[464]	validation_0-mlogloss:1.22244
[465]	validation_0-mlogloss:1.22262
[466]	validation_0-mlogloss:1.22228
[467]	validation_0-mlogloss:1.22265
[468]	validation_0-mlogloss:1.22251
[469]	validation_0-mlogloss:1.22285
[470]	validation_0-mlogloss:1.22335
[471]	validation_0-mlogloss:1.22398
[472]	validation_0-mlogloss:1.22364
[473]	validation_0-mlogloss:1.22396
[474]	validation_0-mlogloss:1.22454
[475]	validation_0-mlogloss:1.22476
[476]	validation_0-mlogloss:1.22469
[477]	validation_0-mlogloss:1.22510
[478]	validation_0-mlogloss:1.22510
[479]	validation_0-mlogloss:1.22552
[480]	validation_0-mlogloss:1.22534
[481]	validation_0-mlogloss:1.22509
[482]	validation_0-mlogloss:1.22542
[483]	validation_0-mlogloss:1.22569
[484]	validation_0-mlogloss:1.22606
[485]	validation_0-mlogloss:1.22646
[486]	validation_0-mlogloss:1.22706
[487]	validation_0-mlogloss:1.22729
[488]	validation_0-mlogloss:1.22775
[489]	validation_0-mlogloss:1.22775
[490]	validation_0-mlogloss:1.22847
[491]	validation_0-mlogloss:1.22880
[492]	validation_0-mlogloss:1.22910
[493]	validation_0-mlogloss:1.22913
[494]	validation_0-mlogloss:1.22908
[495]	validation_0-mlogloss:1.22943
[496]	validation_0-mlogloss:1.22933
[497]	validation_0-mlogloss:1.22960
[498]	validation_0-mlogloss:1.23077
[499]	validation_0-mlogloss:1.23107
[500]	validation_0-mlogloss:1.23069
[501]	validation_0-mlogloss:1.23096
[502]	validation_0-mlogloss:1.23062
[503]	validation_0-mlogloss:1.23085
[504]	validation_0-mlogloss:1.23101
[505]	validation_0-mlogloss:1.23096
[506]	validation_0-mlogloss:1.23087
[507]	validation_0-mlogloss:1.23079
[508]	validation_0-mlogloss:1.23100
[509]	validation_0-mlogloss:1.23119
[510]	validation_0-mlogloss:1.23177
[511]	validation_0-mlogloss:1.23174
[512]	validation_0-mlogloss:1.23154
[513]	validation_0-mlogloss:1.23210
[514]	validation_0-mlogloss:1.23198
[515]	validation_0-mlogloss:1.23172
[516]	validation_0-mlogloss:1.23131
[517]	validation_0-mlogloss:1.23123
[518]	validation_0-mlogloss:1.23121
[519]	validation_0-mlogloss:1.23170
[520]	validation_0-mlogloss:1.23185
[521]	validation_0-mlogloss:1.23231
[522]	validation_0-mlogloss:1.23282
[523]	validation_0-mlogloss:1.23313
[524]	validation_0-mlogloss:1.23270
[525]	validation_0-mlogloss:1.23242
[526]	validation_0-mlogloss:1.23274
[527]	validation_0-mlogloss:1.23285
[528]	validation_0-mlogloss:1.23315
[529]	validation_0-mlogloss:1.23318
[530]	validation_0-mlogloss:1.23325
[531]	validation_0-mlogloss:1.23369
[532]	validation_0-mlogloss:1.23348
[533]	validation_0-mlogloss:1.23332
[534]	validation_0-mlogloss:1.23399
[535]	validation_0-mlogloss:1.23443
[536]	validation_0-mlogloss:1.23528
[537]	validation_0-mlogloss:1.23576
[538]	validation_0-mlogloss:1.23633
[539]	validation_0-mlogloss:1.23628
[540]	validation_0-mlogloss:1.23647
[541]	validation_0-mlogloss:1.23631
[542]	validation_0-mlogloss:1.23666
[543]	validation_0-mlogloss:1.23661
[544]	validation_0-mlogloss:1.23692
[545]	validation_0-mlogloss:1.23681
[546]	validation_0-mlogloss:1.23744
[547]	validation_0-mlogloss:1.23778
[548]	validation_0-mlogloss:1.23830
[549]	validation_0-mlogloss:1.23839
[550]	validation_0-mlogloss:1.23889
[551]	validation_0-mlogloss:1.23889
[552]	validation_0-mlogloss:1.23959
[553]	validation_0-mlogloss:1.23998
[554]	validation_0-mlogloss:1.23988
[555]	validation_0-mlogloss:1.23974
[556]	validation_0-mlogloss:1.24038
[557]	validation_0-mlogloss:1.23999

In [22]:
resultTrainValid()

                     train_acc  valid_acc
LogReg                0.431373   0.382812
KNN                   0.966667   0.367188
Tree                  0.468627   0.296875
Tree with rf          0.886275   0.390625
CatBoostClassifier1   0.827451   0.406250
CatBoostClassifier2   0.698039   0.414062
CatBoostClassifier3   0.458824   0.406250
LGBMClassifier        0.392157   0.390625
XGBClassifier         0.756863   0.359375
CatBoostClassifier1   0.566667   0.414062
CatBoostClassifier2   0.445098   0.445312

In [23]:
resultKFoldMean()

                     mean_acc
LogReg               0.355893
KNN                  0.358907
Tree                 0.384031
Tree with rf         0.341732
CatBoostClassifier1  0.335430
CatBoostClassifier2  0.310420
CatBoostClassifier3  0.347949
LGBMClassifier       0.324512
XGBClassifier        0.326092
CatBoostClassifier1  0.354276
CatBoostClassifier2  0.333887

CatBoostClassifier1	0.615686	0.421875
CatBoostClassifier1	0.327627